#pragma once
#include "physics.h"
#include "broad_phase.h"
#include <vector>

// Exact AABB of the spherical-cap envelope generated by rotating material
// point X from orientation q through the angular extent encoded by q_rel,
// while allowing any world-space rotation axis. The axis stored in q_rel is
// deliberately ignored; its raw sign selects an extent in [0, 2*pi]. An
// extent greater than or equal to pi produces the full-sphere AABB.
AABB spherical_cap_node_aabb(const Vec3& x_com, const Vec4& q, const Vec3& X, const Vec4& q_rel);

// Rigid-node blue boxes: spherical-cap rotation plus padded COM translation.
std::vector<AABB> build_blue_boxes_rb(const std::vector<Vec3>& positions, const std::vector<Vec3>& x_coms, const std::vector<Vec4>& orientations, const std::vector<Vec4>& quaternion_bounds, const std::vector<double>& prev_com_disp, const SimParams& params, const RefMesh& ref_mesh);

int owning_rb_for_node(const std::vector<int>& node_to_rb, int node);

// Rigid-body conflict graph from broad-phase contacts.
void build_rb_contact_adj(const BroadPhase::Cache& bp_cache, const std::vector<int>& node_to_rb, int num_rbs, std::vector<std::vector<int>>& out);

// Mesh-adjacency edges of the conflict graph. Invariant for a fixed mesh.
std::vector<std::vector<int>> build_elastic_adj(const RefMesh& ref_mesh, const VertexTriangleMap& adj, int num_vertices);

// Contact edges of the conflict graph from a BroadPhase-generated cache.
void build_contact_adj(const BroadPhase::Cache& bp_cache, int num_vertices, std::vector<std::vector<int>>& out);

// Sorted per-vertex union of two sorted neighbor lists.
void union_adjacency(const std::vector<std::vector<int>>& a, const std::vector<std::vector<int>>& b,  std::vector<std::vector<int>>& out);

void greedy_color_conflict_graph(const std::vector<std::vector<int>>& graph, std::vector<std::vector<int>>& groups);
