#include "make_shape.h"
#include "physics.h"
#include "solver.h"
#include "broad_phase.h"
#include <gtest/gtest.h>
#include <vector>

// Check that one Gauss-Seidel sweep in serial and parallel produce the same
// result given the same input. Within a color group, vertices are independent
// by construction, so parallel should be bit-identical to serial when iterating
// in the same order within each group.
// We allow a small floating-point tolerance for any OMP reduction reordering.
static constexpr double kTol = 1e-10;

static void build_scene(RefMesh& ref_mesh, DeformedState& state,
                        std::vector<Pin>& pins, VertexTriangleMap& adj,
                        SimParams& params, std::vector<Vec2>& X) {
    params.fps             = 30.0;
    params.substeps        = 1;
    params.mu              = 10.0;
    params.lambda          = 10.0;
    params.density         = 1.0;
    params.thickness       = 0.1;
    params.kpin            = 1e7;
    params.gravity         = Vec3(0.0, -9.81, 0.0);
    params.max_global_iters = 100;
    params.tol_abs         = 1e-6;
    params.step_weight     = 1.0;
    params.use_parallel    = false;

    clear_model(ref_mesh, state, X, pins);
    int nx = 10, ny = 10;
    int base = build_square_mesh(ref_mesh, state, X, nx, ny, 2.0, 2.0, Vec3(0.2, -0.1, 0.3));
    state.velocities.assign(state.deformed_positions.size(), Vec3::Zero());
    append_pin(pins, base + ny * (nx + 1),      state.deformed_positions);
    append_pin(pins, base + ny * (nx + 1) + nx, state.deformed_positions);
    ref_mesh.build_lumped_mass(params.density, params.thickness);
    adj = build_incident_triangle_map(ref_mesh.tris);
}

TEST(ParallelSerialConsistency, OneSweepMatchesSerialAtFrame50) {
    RefMesh ref_mesh; VertexTriangleMap adj;
    std::vector<Pin> pins; SimParams params; std::vector<Vec2> X;
    DeformedState state;
    build_scene(ref_mesh, state, pins, adj, params, X);

    // Load frame 50 state from checkpoint generated by generate_golden
    const std::string checkpoint_dir = std::string(GOLDEN_DIR) + "/frame_50_checkpoint";
    ASSERT_TRUE(deserialize_state(checkpoint_dir, 50, state))
        << "Failed to load frame 50 checkpoint — run generate_golden first";

    const auto color_groups = greedy_color(build_vertex_adjacency_map(ref_mesh.tris),
                                           static_cast<int>(state.deformed_positions.size()));
    // Params for the single-sweep comparison
    SimParams sweep_params = params;
    sweep_params.max_global_iters = 1;   // exactly one sweep
    sweep_params.tol_abs          = 0.0; // never early-exit

    // Build xhat from frame-50 state (same for both runs)
    std::vector<Vec3> xhat;
    build_xhat(xhat, state.deformed_positions, state.velocities, sweep_params.dt());

    // --- Serial: one sweep via global_gauss_seidel_solver with use_parallel=false ---
    std::vector<Vec3> serial_x = state.deformed_positions;
    {
        SimParams p = sweep_params; p.use_parallel = false;
        BroadPhase bp;
        global_gauss_seidel_solver(ref_mesh, adj, pins, p, serial_x, xhat,
                                   bp, state.velocities, color_groups);
    }

    // --- Parallel: one sweep through color groups, vertices within group in parallel ---
    std::vector<Vec3> parallel_x = state.deformed_positions;
    {
        SimParams p = sweep_params; p.use_parallel = true;
        BroadPhase bp;
        global_gauss_seidel_solver(ref_mesh, adj, pins, p, parallel_x, xhat,
                                   bp, state.velocities, color_groups);
    }

    // --- Compare: should be identical since vertices in same color group are independent ---
    ASSERT_EQ(serial_x.size(), parallel_x.size());
    for (int i = 0; i < static_cast<int>(serial_x.size()); ++i) {
        EXPECT_NEAR(serial_x[i].x(), parallel_x[i].x(), kTol) << "vertex=" << i << " x mismatch";
        EXPECT_NEAR(serial_x[i].y(), parallel_x[i].y(), kTol) << "vertex=" << i << " y mismatch";
        EXPECT_NEAR(serial_x[i].z(), parallel_x[i].z(), kTol) << "vertex=" << i << " z mismatch";
    }
}
