// Self-contained sandbox generated by consolidating the project sources into one file.
#include <Eigen/Dense>
#include <Eigen/Geometry>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace fs = std::__fs::filesystem;

// ===== BEGIN IPC_math.h =====

#include <Eigen/Dense>
#include <array>

// Type aliases
using Vec2   = Eigen::Vector2d;
using Vec3   = Eigen::Vector3d;
using Vec6   = Eigen::Matrix<double, 6, 1>;
using Vec9   = Eigen::Matrix<double, 9, 1>;
using Vec12  = Eigen::Matrix<double, 12, 1>;
using Mat22  = Eigen::Matrix2d;
using Mat32  = Eigen::Matrix<double, 3, 2>;
using Mat33  = Eigen::Matrix3d;
using Mat39  = Eigen::Matrix<double, 3, 9>;
using Mat66  = Eigen::Matrix<double, 6, 6>;
using Mat312 = Eigen::Matrix<double, 3, 12>;
using Mat12  = Eigen::Matrix<double, 12, 12>;

// Triangle definitions
struct TriangleRest {
    Vec2 X[3];
};

struct TriangleDef {
    Vec3 x[3];
};

// Utility functions
Mat33 matrix3d_inverse(const Mat33& H);

TriangleDef ZeroTriangleDef();

TriangleDef add_scale(const TriangleDef& a, const TriangleDef& b, double s);

Vec9 flatten_def(const TriangleDef& def);

double get_dof(const TriangleDef& def, int node, int comp);

void set_dof(TriangleDef& def, int node, int comp, double value);

double clamp_scalar(double v, double lo, double hi);

Vec3 segment_closest_point(const Vec3& x, const Vec3& a, const Vec3& b, double& t);

std::array<double, 3> triangle_plane_barycentric_coordinates(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double eps = 1.0e-12);
// ===== END IPC_math.h =====

// ===== BEGIN node_triangle_distance.h =====

#include <array>
#include <string>

enum class NodeTriangleRegion{
    FaceInterior, Edge12, Edge23, Edge31, Vertex1, Vertex2, Vertex3, DegenerateTriangle
};

std::string to_string(NodeTriangleRegion region);

struct NodeTriangleDistanceResult{
    Vec3 closest_point;
    Vec3 tilde_x; // projection of x
    Vec3 normal;
    std::array<double, 3> barycentric_tilde_x;
    double phi;
    double distance;
    NodeTriangleRegion region;
};

NodeTriangleDistanceResult node_triangle_distance(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double eps = 1.0e-12);
// ===== END node_triangle_distance.h =====

// ===== BEGIN segment_segment_distance.h =====

#include <array>
#include <string>

// Regions of the (s,t) parameter square [0,1]^2
enum class SegmentSegmentRegion{
    Interior, // 0 < s* < 1, 0 < t* < 1
    Edge_s0,  // s = 0, point x1 vs segment (x3,x4)
    Edge_s1, // s = 1, point x2 vs segment (x3,x4)
    Edge_t0,  // t = 0, point x3 vs segment (x1,x2)
    Edge_t1, // t = 1, point x4 vs segment (x1,x2)
    Corner_s0t0,  // (s,t) = (0,0), vertex x1 vs vertex x3
    Corner_s0t1, // (s,t) = (0,1), vertex x1 vs vertex x4
    Corner_s1t0, // (s,t) = (1,0), vertex x2 vs vertex x3
    Corner_s1t1, // (s,t) = (1,1), vertex x2 vs vertex x4
    ParallelSegments // segments are (nearly) parallel
};

std::string to_string(SegmentSegmentRegion region);

struct SegmentSegmentDistanceResult{
    Vec3 closest_point_1; // closest point on segment 1
    Vec3 closest_point_2; // closest point on segment 2
    double s; // parameter on segment 1: p(s) = (1-s)*x1 + s*x2
    double t; // parameter on segment 2: q(t) = (1-t)*x3 + t*x4
    double distance;
    SegmentSegmentRegion region;
};

SegmentSegmentDistanceResult segment_segment_distance(const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4, double eps = 1.0e-12);
// ===== END segment_segment_distance.h =====

// ===== BEGIN corotated_energy.h =====

struct CorotatedCache32 {
    Mat22 S;
    Mat22 SInv;
    Mat32 R;
    Mat22 FTFinv;
    Mat32 FFTFInv;      // F * FTFinv          — cached for dPdF
    Mat33 FFTFInvFT;    // F * FTFinv * F^T     — cached for dPdF
    double J;
    double traceS;
};

CorotatedCache32 buildCorotatedCache(const Mat32& F);

double PsiCorotated32(const CorotatedCache32& cache, const Mat32& F, double mu, double lambda);
Mat32  PCorotated32(const CorotatedCache32& cache, const Mat32& F, double mu, double lambda);
void   dPdFCorotated32(const CorotatedCache32& cache, double mu, double lambda, Mat66& dPdF);

double corotated_energy(double ref_area, const Mat22& Dm_inv, const TriangleDef& def, double mu, double lambda);

using ShapeGrads = std::array<Vec2, 3>;
ShapeGrads shape_function_gradients(const Mat22& Dm_inv);

Vec3  corotated_node_gradient(const Mat32& P, double ref_area, const ShapeGrads& gradN, int node);
Mat39 corotated_node_hessian(const Mat66& dPdF, double ref_area, const ShapeGrads& gradN, int node);

// ===== END corotated_energy.h =====

// ===== BEGIN barrier_energy.h =====


//  Scalar barrier
double scalar_barrier(double delta, double d_hat);

//  Scalar barrier gradient  db/d(delta)
double scalar_barrier_gradient(double delta, double d_hat);

//  Scalar barrier hessian  d2b/d(delta)2
double scalar_barrier_hessian(double delta, double d_hat);

// ====================================================================
//  Node--triangle barrier
//  DOF ordering: p = 0(x), 1(x1), 2(x2), 3(x3)
// ====================================================================

double node_triangle_barrier(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double d_hat, double eps = 1.0e-12);

// Single-DOF gradient: returns dE/d(y_dof)
Vec3 node_triangle_barrier_gradient(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double d_hat, int dof, double eps = 1.0e-12);

// Single-DOF hessian row: returns 3x12 block d^2E/(d(y_dof) d(y_all))
Mat312 node_triangle_barrier_hessian(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double d_hat, int dof, double eps = 1.0e-12);

// ====================================================================
//  Segment--segment barrier
//  DOF ordering: p = 0(x1), 1(x2), 2(x3), 3(x4)
// ====================================================================

double segment_segment_barrier(const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4, double d_hat, double eps = 1.0e-12);

// Single-DOF gradient: returns dE/d(y_dof)
Vec3 segment_segment_barrier_gradient(const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4, double d_hat, int dof, double eps = 1.0e-12);

// Single-DOF hessian row: returns 3x12 block d^2E/(d(y_dof) d(y_all))
Mat312 segment_segment_barrier_hessian(const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4, double d_hat, int dof, double eps = 1.0e-12);

// Combined: one distance evaluation for both gradient and hessian row
std::pair<Vec3, Mat312> node_triangle_barrier_gradient_and_hessian(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double d_hat, int dof, double eps = 1.0e-12);
std::pair<Vec3, Mat312> segment_segment_barrier_gradient_and_hessian(const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4, double d_hat, int dof, double eps = 1.0e-12);
// ===== END barrier_energy.h =====

// ===== BEGIN physics.h =====
#include <vector>

struct Tri { int v[3]; };

struct Pin {
    int vertex_index = -1;
    Vec3 target_position = Vec3::Zero();
};

struct SimParams {
    double dt{}, mu{}, lambda{}, density{}, thickness{}, kpin{}, tol_abs{}, step_weight{};
    double d_hat{0.0};          // barrier activation distance (0 = no barrier)
    Vec3 gravity = Vec3::Zero();
    int max_global_iters{};
};

struct DeformedState {
    std::vector<Vec3> deformed_positions;
    std::vector<Vec3> velocities;
};

struct RefMesh {
    std::vector<Tri> tris;
    std::vector<Mat22> Dm_inverse;
    std::vector<double> area;
    std::vector<double> mass;
    size_t num_positions;

    inline void initialize(const std::vector<Vec2>& X){
        num_positions = X.size();
        compute_dm_inverse(X);
    }

    inline void compute_dm_inverse(const std::vector<Vec2>& X){
        Dm_inverse.resize(tris.size());
        area.resize(tris.size());
        for(size_t t=0;t<tris.size();t++){
            const Vec2& X0 = X[tris[t].v[0]];
            const Vec2& X1 = X[tris[t].v[1]];
            const Vec2& X2 = X[tris[t].v[2]];

            Mat22 Dm_local;
            Dm_local.col(0) = X1 - X0;
            Dm_local.col(1) = X2 - X0;
            area[t]=0.5 * std::abs(Dm_local.determinant());
            Dm_inverse[t]=Dm_local.inverse();
        }
    }

    inline void build_lumped_mass(double density, double thickness) {
        mass.assign(num_positions, 0.0);

        for (size_t t=0;t<tris.size();t++) {
            double m = density * area[t] * thickness;
            double mv = m / 3.0;
            for (int a : tris[t].v) mass[a] += mv;
        }
    }
};

struct VertexAdjacency {
    std::vector<std::vector<int>> incident_triangle_indices;
};

double triangle_ref_area_2d(const RefMesh& ref_mesh, const std::vector<Vec2>& X, const Tri& tri);

VertexAdjacency build_vertex_adjacency(const RefMesh& ref_mesh);

double compute_incremental_potential_no_barrier(const RefMesh& ref_mesh, const std::vector<Pin>& pins, const SimParams& params, const std::vector<Vec3>& x, const std::vector<Vec3>& xhat);

std::pair<Vec3, Mat33> compute_local_gradient_and_hessian_no_barrier(int vi, const RefMesh& ref_mesh, const VertexAdjacency& adj, const std::vector<Pin>& pins, const SimParams& params, const std::vector<Vec3>& x, const std::vector<Vec3>& xhat);

Vec3 compute_local_gradient_no_barrier(int vi, const RefMesh& ref_mesh, const VertexAdjacency& adj, const std::vector<Pin>& pins, const SimParams& params, const std::vector<Vec3>& x, const std::vector<Vec3>& xhat);

double compute_global_residual(const RefMesh& ref_mesh, const VertexAdjacency& adj, const std::vector<Pin>& pins, const SimParams& params, const std::vector<Vec3>& x, const std::vector<Vec3>& xhat);

// ===== END physics.h =====

// ===== BEGIN make_shape.h =====
#include <unordered_map>
#include <vector>

TriangleRest make_rest_triangle(const std::vector<Vec2>& X, const Tri& tri);

TriangleDef make_def_triangle(const std::vector<Vec3>& x, const Tri& tri);

void build_xhat(std::vector<Vec3>& xhat, const std::vector<Vec3>& x, const std::vector<Vec3>& v, double dt);

void update_velocity(std::vector<Vec3>& v, const std::vector<Vec3>& xnew, const std::vector<Vec3>& xold, double dt);

void clear_model(RefMesh& ref_mesh, DeformedState& state, std::vector<Vec2>& X, std::vector<Pin>& pins);

int build_single_triangle(RefMesh& ref_mesh, DeformedState& state, std::vector<Vec2>& X,
                          const Vec2& X0, const Vec2& X1, const Vec2& X2,
                          const Vec3& x0, const Vec3& x1, const Vec3& x2);

void append_pin(std::vector<Pin>& pins, int vertex_index, const std::vector<Vec3>& x);

int build_square_mesh(RefMesh& ref_mesh, DeformedState& state, std::vector<Vec2>& X, int nx, int ny, double width, double height, const Vec3& origin);

// Maps each vertex index to all positions in the flat index buffer where it appears.
// e.g. for [0,1,2,1,2,5]: {0:[0], 1:[1,3], 2:[2,4], 5:[5]}
std::unordered_map<int, std::vector<int>> build_incident_triangle_map(const std::vector<int>& indices);
// ===== END make_shape.h =====

// ===== BEGIN solver.h =====
#include <vector>

struct SolverResult {
    double initial_residual = 0.0;
    double final_residual = 0.0;
    int iterations = 0;
};

void update_one_vertex(int vi, const RefMesh& ref_mesh, const VertexAdjacency& adj,
                       const std::vector<Pin>& pins, const SimParams& params, const std::vector<Vec3>& xhat, std::vector<Vec3>& x);

SolverResult global_gauss_seidel_solver(const RefMesh& ref_mesh, const VertexAdjacency& adj,
                                        const std::vector<Pin>& pins, const SimParams& params, std::vector<Vec3>& xnew,
                                        const std::vector<Vec3>& xhat, std::vector<double>* residual_history = nullptr);
// ===== END solver.h =====

// ===== BEGIN visualization.h =====
#include <string>
#include <vector>

void export_obj(const std::string& filename, const std::vector<Vec3>& x, const std::vector<Tri>& tris);

void export_frame(const std::string& outdir, int frame, const std::vector<Vec3>& x, const std::vector<Tri>& tris);
// ===== END visualization.h =====

// ===== BEGIN IPC_math.cpp =====
#include <algorithm>
#include <cmath>
#include <stdexcept>

Mat33 matrix3d_inverse(const Mat33& H) {

    double det = H(0,0)*(H(1,1)*H(2,2) - H(1,2)*H(2,1))
                 - H(0,1)*(H(1,0)*H(2,2) - H(1,2)*H(2,0))
                 + H(0,2)*(H(1,0)*H(2,1) - H(1,1)*H(2,0));

    if (std::abs(det) < 1e-12) throw std::runtime_error("Singular matrix in matrix3d_inverse().");

    double inv_det = 1.0 / det;
    Mat33 inv;

    inv(0,0) =  (H(1,1)*H(2,2) - H(1,2)*H(2,1));
    inv(0,1) = -(H(0,1)*H(2,2) - H(0,2)*H(2,1));
    inv(0,2) =  (H(0,1)*H(1,2) - H(0,2)*H(1,1));
    inv(1,0) = -(H(1,0)*H(2,2) - H(1,2)*H(2,0));
    inv(1,1) =  (H(0,0)*H(2,2) - H(0,2)*H(2,0));
    inv(1,2) = -(H(0,0)*H(1,2) - H(0,2)*H(1,0));
    inv(2,0) =  (H(1,0)*H(2,1) - H(1,1)*H(2,0));
    inv(2,1) = -(H(0,0)*H(2,1) - H(0,1)*H(2,0));
    inv(2,2) =  (H(0,0)*H(1,1) - H(0,1)*H(1,0));

    return inv * inv_det;
}

TriangleDef ZeroTriangleDef() {
    TriangleDef out;
    out.x[0].setZero();
    out.x[1].setZero();
    out.x[2].setZero();
    return out;
}

TriangleDef add_scale(const TriangleDef& a, const TriangleDef& b, double s) {
    TriangleDef out;
    for (int i = 0; i < 3; ++i) out.x[i] = a.x[i] + s * b.x[i];
    return out;
}

Vec9 flatten_def(const TriangleDef& def) {
    Vec9 out;
    for (int i = 0; i < 3; ++i) out.segment<3>(3 * i) = def.x[i];
    return out;
}

double get_dof(const TriangleDef& def, int node, int comp) {
    return def.x[node](comp);
}

void set_dof(TriangleDef& def, int node, int comp, double value) {
    def.x[node](comp) = value;
}

double clamp_scalar(double v, double lo, double hi) {
    return std::max(lo, std::min(v, hi));
}

Vec3 segment_closest_point(const Vec3& x, const Vec3& a, const Vec3& b, double& t) {
    const Vec3 ab = b - a;
    const double ab2 = ab.dot(ab);

    if (ab2 <= 0.0) {
        t = 0.0;
        return a;
    }

    t = (x - a).dot(ab) / ab2;
    t = clamp_scalar(t, 0.0, 1.0);
    return a + t * ab;
}

std::array<double, 3> triangle_plane_barycentric_coordinates(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double eps){
    const Vec3 e1 = x2 - x1;
    const Vec3 e2 = x3 - x1;
    const Vec3 r  = x - x1;

    const double a11 = e1.dot(e1);
    const double a12 = e1.dot(e2);
    const double a22 = e2.dot(e2);

    const double b1 = r.dot(e1);
    const double b2 = r.dot(e2);

    const double det = a11 * a22 - a12 * a12;

    if (std::abs(det) <= eps) {
        return {{0.0, 0.0, 0.0}};
    }

    const double alpha = ( b1 * a22 - b2 * a12) / det;
    const double beta  = (-b1 * a12 + b2 * a11) / det;

    const double lambda1 = 1.0 - alpha - beta;
    const double lambda2 = alpha;
    const double lambda3 = beta;

    return {{lambda1, lambda2, lambda3}};
}
// ===== END IPC_math.cpp =====

// ===== BEGIN node_triangle_distance.cpp =====

#include <cmath>
#include <limits>

std::string to_string(NodeTriangleRegion region){
    switch (region) {
        case NodeTriangleRegion::FaceInterior: return "FaceInterior";
        case NodeTriangleRegion::Edge12: return "Edge12";
        case NodeTriangleRegion::Edge23: return "Edge23";
        case NodeTriangleRegion::Edge31: return "Edge31";
        case NodeTriangleRegion::Vertex1: return "Vertex1";
        case NodeTriangleRegion::Vertex2: return "Vertex2";
        case NodeTriangleRegion::Vertex3: return "Vertex3";
        case NodeTriangleRegion::DegenerateTriangle: return "DegenerateTriangle";
        default: return "Unknown";
    }
}

NodeTriangleDistanceResult node_triangle_distance(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double eps){
    NodeTriangleDistanceResult out;
    out.closest_point = Vec3::Zero();
    out.tilde_x = Vec3::Zero();
    out.normal = Vec3::Zero();
    out.barycentric_tilde_x = {{0.0, 0.0, 0.0}};
    out.phi = 0.0;
    out.distance = 0.0;
    out.region = NodeTriangleRegion::DegenerateTriangle;

    const Vec3 e12 = x2 - x1;
    const Vec3 e13 = x3 - x1;
    const Vec3 n_raw = e12.cross(e13);
    const double n_norm = n_raw.norm();

    if (n_norm <= eps) {
        double t12 = 0.0, t23 = 0.0, t31 = 0.0;
        const Vec3 q12 = segment_closest_point(x, x1, x2, t12);
        const Vec3 q23 = segment_closest_point(x, x2, x3, t23);
        const Vec3 q31 = segment_closest_point(x, x3, x1, t31);

        const double d12 = (x - q12).norm();
        const double d23 = (x - q23).norm();
        const double d31 = (x - q31).norm();

        if (d12 <= d23 && d12 <= d31) {
            out.closest_point = q12;
            out.distance = d12;
        } else if (d23 <= d12 && d23 <= d31) {
            out.closest_point = q23;
            out.distance = d23;
        } else {
            out.closest_point = q31;
            out.distance = d31;
        }

        out.tilde_x = out.closest_point;
        return out;
    }

    const Vec3 n = n_raw / n_norm;
    const double phi = n.dot(x - x1);
    const Vec3 tilde_x = x - phi * n;

    out.normal = n;
    out.phi = phi;
    out.tilde_x = tilde_x;

    const auto lambda = triangle_plane_barycentric_coordinates(tilde_x, x1, x2, x3, eps);
    out.barycentric_tilde_x = lambda;

    const double l1 = lambda[0];
    const double l2 = lambda[1];
    const double l3 = lambda[2];

    if (l1 >= 0.0 && l2 >= 0.0 && l3 >= 0.0) {
        out.closest_point = tilde_x;
        out.distance = std::abs(phi);
        out.region = NodeTriangleRegion::FaceInterior;
        return out;
    }

    // Vertex regions: two barycentric coordinates <= 0
    // Vertex 1: l2 <= 0 and l3 <= 0
    if (l2 <= 0.0 && l3 <= 0.0) {
        out.closest_point = x1;
        out.distance = (x - x1).norm();
        out.region = NodeTriangleRegion::Vertex1;
        return out;
    }

    // Vertex 2: l3 <= 0 and l1 <= 0
    if (l3 <= 0.0 && l1 <= 0.0) {
        out.closest_point = x2;
        out.distance = (x - x2).norm();
        out.region = NodeTriangleRegion::Vertex2;
        return out;
    }

    // Vertex 3: l1 <= 0 and l2 <= 0
    if (l1 <= 0.0 && l2 <= 0.0) {
        out.closest_point = x3;
        out.distance = (x - x3).norm();
        out.region = NodeTriangleRegion::Vertex3;
        return out;
    }

    // Edge regions: exactly one barycentric coordinate < 0
    if (l3 < 0.0) {
        double t = 0.0;
        out.closest_point = segment_closest_point(tilde_x, x1, x2, t);
        out.distance = (x - out.closest_point).norm();
        out.region = NodeTriangleRegion::Edge12;
        return out;
    }

    if (l1 < 0.0) {
        double t = 0.0;
        out.closest_point = segment_closest_point(tilde_x, x2, x3, t);
        out.distance = (x - out.closest_point).norm();
        out.region = NodeTriangleRegion::Edge23;
        return out;
    }

    if (l2 < 0.0) {
        double t = 0.0;
        out.closest_point = segment_closest_point(tilde_x, x3, x1, t);
        out.distance = (x - out.closest_point).norm();
        out.region = NodeTriangleRegion::Edge31;
        return out;
    }

    // numerical fallback
    {
        double t12 = 0.0, t23 = 0.0, t31 = 0.0;
        const Vec3 q12 = segment_closest_point(tilde_x, x1, x2, t12);
        const Vec3 q23 = segment_closest_point(tilde_x, x2, x3, t23);
        const Vec3 q31 = segment_closest_point(tilde_x, x3, x1, t31);

        const double d12 = (x - q12).norm();
        const double d23 = (x - q23).norm();
        const double d31 = (x - q31).norm();

        if (d12 <= d23 && d12 <= d31) {
            out.closest_point = q12;
            out.distance = d12;
            out.region = NodeTriangleRegion::Edge12;
        } else if (d23 <= d12 && d23 <= d31) {
            out.closest_point = q23;
            out.distance = d23;
            out.region = NodeTriangleRegion::Edge23;
        } else {
            out.closest_point = q31;
            out.distance = d31;
            out.region = NodeTriangleRegion::Edge31;
        }
    }

    return out;
}
// ===== END node_triangle_distance.cpp =====

// ===== BEGIN segment_segment_distance.cpp =====

#include <cmath>
#include <limits>

std::string to_string(SegmentSegmentRegion region){
    switch (region) {
        case SegmentSegmentRegion::Interior: return "Interior";
        case SegmentSegmentRegion::Edge_s0: return "Edge_s0";
        case SegmentSegmentRegion::Edge_s1: return "Edge_s1";
        case SegmentSegmentRegion::Edge_t0: return "Edge_t0";
        case SegmentSegmentRegion::Edge_t1: return "Edge_t1";
        case SegmentSegmentRegion::Corner_s0t0: return "Corner_s0t0";
        case SegmentSegmentRegion::Corner_s0t1:  return "Corner_s0t1";
        case SegmentSegmentRegion::Corner_s1t0:  return "Corner_s1t0";
        case SegmentSegmentRegion::Corner_s1t1: return "Corner_s1t1";
        case SegmentSegmentRegion::ParallelSegments: return "ParallelSegments";
        default: return "Unknown";
    }
}

// Given fixed s, find optimal t on [0,1] and return distance.
static double optimal_t_for_fixed_s(const Vec3& x1, const Vec3& a, const Vec3& x3, const Vec3& b, double s, double C, double& t_out){
    const Vec3 p = x1 + s * a;
    if (C <= 0.0) {
        t_out = 0.0;
    } else {
        t_out = clamp_scalar((p - x3).dot(b) / C, 0.0, 1.0);
    }
    const Vec3 q = x3 + t_out * b;
    return (p - q).norm();
}

// Given fixed t, find optimal s on [0,1] and return distance.
static double optimal_s_for_fixed_t(const Vec3& x1, const Vec3& a, const Vec3& x3, const Vec3& b, double t, double A, double& s_out){
    const Vec3 q = x3 + t * b;
    if (A <= 0.0) {
        s_out = 0.0;
    } else {
        s_out = clamp_scalar((q - x1).dot(a) / A, 0.0, 1.0);
    }
    const Vec3 p = x1 + s_out * a;
    return (p - q).norm();
}

// Classify an (s,t) pair into a region.
static SegmentSegmentRegion classify(double s, double t, double tol = 1e-14){
    const bool s_at_0 = (s <= tol);
    const bool s_at_1 = (s >= 1.0 - tol);
    const bool t_at_0 = (t <= tol);
    const bool t_at_1 = (t >= 1.0 - tol);

    if (s_at_0 && t_at_0) return SegmentSegmentRegion::Corner_s0t0;
    if (s_at_0 && t_at_1) return SegmentSegmentRegion::Corner_s0t1;
    if (s_at_1 && t_at_0) return SegmentSegmentRegion::Corner_s1t0;
    if (s_at_1 && t_at_1) return SegmentSegmentRegion::Corner_s1t1;

    if (s_at_0) return SegmentSegmentRegion::Edge_s0;
    if (s_at_1) return SegmentSegmentRegion::Edge_s1;
    if (t_at_0) return SegmentSegmentRegion::Edge_t0;
    if (t_at_1) return SegmentSegmentRegion::Edge_t1;

    return SegmentSegmentRegion::Interior;
}

SegmentSegmentDistanceResult segment_segment_distance(const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4, double eps){
    SegmentSegmentDistanceResult out;
    out.closest_point_1 = Vec3::Zero();
    out.closest_point_2 = Vec3::Zero();
    out.s = 0.0;
    out.t = 0.0;
    out.distance = 0.0;
    out.region = SegmentSegmentRegion::ParallelSegments;

    // a = x2 - x1,  b = x4 - x3,  c = x1 - x3
    const Vec3 a = x2 - x1;
    const Vec3 b = x4 - x3;
    const Vec3 c = x1 - x3;

    const double A = a.dot(a);  // ||a||^2
    const double B = a.dot(b);  // a . b
    const double C = b.dot(b);  // ||b||^2
    const double D = a.dot(c);  // a . c
    const double E = b.dot(c);  // b . c

    const double Delta = A * C - B * B;  // = ||a x b||^2

    // Non-parallel case: Delta > 0
    // Solve:  s* = (BE - CD) / Delta,  t* = (AE - BD) / Delta
    if (Delta > eps * eps) {
        const double s_unc = (B * E - C * D) / Delta;
        const double t_unc = (A * E - B * D) / Delta;

        // If the unconstrained solution lies inside [0,1]^2, we are done.
        if (s_unc >= 0.0 && s_unc <= 1.0 && t_unc >= 0.0 && t_unc <= 1.0) {
            out.s = s_unc;
            out.t = t_unc;
            out.closest_point_1 = x1 + out.s * a;
            out.closest_point_2 = x3 + out.t * b;
            out.distance = (out.closest_point_1 - out.closest_point_2).norm();
            out.region = SegmentSegmentRegion::Interior;
            return out;
        }

        // Unconstrained minimizer outside [0,1]^2. Check all four edges.
        double best_dist = std::numeric_limits<double>::max();
        double best_s = 0.0, best_t = 0.0;

        { // Edge s = 0
            double t_cand = 0.0;
            const double d = optimal_t_for_fixed_s(x1, a, x3, b, 0.0, C, t_cand);
            if (d < best_dist) { best_dist = d; best_s = 0.0; best_t = t_cand; }
        }
        { // Edge s = 1
            double t_cand = 0.0;
            const double d = optimal_t_for_fixed_s(x1, a, x3, b, 1.0, C, t_cand);
            if (d < best_dist) { best_dist = d; best_s = 1.0; best_t = t_cand; }
        }
        { // Edge t = 0
            double s_cand = 0.0;
            const double d = optimal_s_for_fixed_t(x1, a, x3, b, 0.0, A, s_cand);
            if (d < best_dist) { best_dist = d; best_s = s_cand; best_t = 0.0; }
        }
        { // Edge t = 1
            double s_cand = 0.0;
            const double d = optimal_s_for_fixed_t(x1, a, x3, b, 1.0, A, s_cand);
            if (d < best_dist) { best_dist = d; best_s = s_cand; best_t = 1.0; }
        }

        out.s = best_s;
        out.t = best_t;
        out.closest_point_1 = x1 + out.s * a;
        out.closest_point_2 = x3 + out.t * b;
        out.distance = best_dist;
        out.region = classify(out.s, out.t);
        return out;
    }

    // Parallel / degenerate case: Delta ～ 0. Check all four boundary edges.
    out.region = SegmentSegmentRegion::ParallelSegments;

    double best_dist = std::numeric_limits<double>::max();
    double best_s = 0.0, best_t = 0.0;

    { // Edge s = 0
        double t_cand = 0.0;
        const double d = optimal_t_for_fixed_s(x1, a, x3, b, 0.0, C, t_cand);
        if (d < best_dist) { best_dist = d; best_s = 0.0; best_t = t_cand; }
    }
    { // Edge s = 1
        double t_cand = 0.0;
        const double d = optimal_t_for_fixed_s(x1, a, x3, b, 1.0, C, t_cand);
        if (d < best_dist) { best_dist = d; best_s = 1.0; best_t = t_cand; }
    }
    { // Edge t = 0
        double s_cand = 0.0;
        const double d = optimal_s_for_fixed_t(x1, a, x3, b, 0.0, A, s_cand);
        if (d < best_dist) { best_dist = d; best_s = s_cand; best_t = 0.0; }
    }
    { // Edge t = 1
        double s_cand = 0.0;
        const double d = optimal_s_for_fixed_t(x1, a, x3, b, 1.0, A, s_cand);
        if (d < best_dist) { best_dist = d; best_s = s_cand; best_t = 1.0; }
    }

    out.s = best_s;
    out.t = best_t;
    out.closest_point_1 = x1 + out.s * a;
    out.closest_point_2 = x3 + out.t * b;
    out.distance = best_dist;

    return out;
}
// ===== END segment_segment_distance.cpp =====

// ===== BEGIN corotated_energy.cpp =====

#include <algorithm>
#include <cmath>
#include <stdexcept>

inline int flatF(int a, int b) {
    return 2 * a + b;
}

Mat32 Ds(const TriangleDef& tri) {
    Mat32 out;
    out.col(0) = tri.x[1] - tri.x[0];
    out.col(1) = tri.x[2] - tri.x[0];
    return out;
}

// Shared eigendecomposition cache — FFTFInv and FFTFInvFT pre-computed
CorotatedCache32 buildCorotatedCache(const Mat32& F) {
    CorotatedCache32 c;

    Mat22 C = F.transpose() * F;
    Eigen::SelfAdjointEigenSolver<Mat22> es(C);
    if (es.info() != Eigen::Success)
        throw std::runtime_error("Eigen decomposition failed in buildCorotatedCache.");

    Mat22 U     = es.eigenvectors();
    Eigen::Vector2d evals = es.eigenvalues();
    evals(0) = std::max(evals(0), 1e-12);
    evals(1) = std::max(evals(1), 1e-12);

    Mat22 S_diag  = Mat22::Zero();
    S_diag(0, 0)  = std::sqrt(evals(0));
    S_diag(1, 1)  = std::sqrt(evals(1));

    c.S         = U * S_diag * U.transpose();
    c.SInv      = c.S.inverse();
    c.R         = F * c.SInv;
    c.J         = S_diag(0, 0) * S_diag(1, 1);
    c.traceS    = c.S.trace();
    c.FTFinv    = C.inverse();
    c.FFTFInv   = F * c.FTFinv;
    c.FFTFInvFT = c.FFTFInv * F.transpose();

    return c;
}

// Cached Psi functions
double PsiCorotated32(const CorotatedCache32& cache, const Mat32& F, double mu, double lambda) {
    return mu * (F - cache.R).squaredNorm() + 0.5 * lambda * (cache.J - 1.0) * (cache.J - 1.0);
}

Mat32 PCorotated32(const CorotatedCache32& cache, const Mat32& F, double mu, double lambda) {
    return 2.0 * mu * (F - cache.R) + lambda * (cache.J - 1.0) * cache.J * cache.FFTFInv;
}

void dPdFCorotated32(const CorotatedCache32& cache, double mu, double lambda, Mat66& dPdF) {
    const Mat22& SInv      = cache.SInv;
    const Mat32& R         = cache.R;
    const Mat22& FTFinv    = cache.FTFinv;
    const Mat32& FFTFInv   = cache.FFTFInv;
    const Mat33& FFTFInvFT = cache.FFTFInvFT;
    double J      = cache.J;
    double traceS = cache.traceS;

    Mat33 RRT = R * R.transpose();

    Mat32 Re;
    Re(0,0) =  R(0,1); Re(0,1) = -R(0,0);
    Re(1,0) =  R(1,1); Re(1,1) = -R(1,0);
    Re(2,0) =  R(2,1); Re(2,1) = -R(2,0);

    Vec6 dcdF;
    dcdF << -R(0,1) / traceS,  R(0,0) / traceS,
            -R(1,1) / traceS,  R(1,0) / traceS,
            -R(2,1) / traceS,  R(2,0) / traceS;

    Mat66 dRdF = Mat66::Zero();
    static constexpr int idx[12] = {0,0, 0,1, 1,0, 1,1, 2,0, 2,1};

    for (int c1 = 0; c1 < 6; ++c1) {
        for (int c2 = 0; c2 < 6; ++c2) {
            int m = idx[2*c1], n = idx[2*c1+1];
            int i = idx[2*c2], j = idx[2*c2+1];
            double v = 0.0;
            if (m == i) v += SInv(j, n);
            v -= RRT(m, i) * SInv(j, n);
            v -= dcdF(c2) * Re(m, n);
            dRdF(c1, c2) = v;
        }
    }

    dPdF.setZero();
    for (int c1 = 0; c1 < 6; ++c1) {
        for (int c2 = 0; c2 < 6; ++c2) {
            int m = idx[2*c1], n = idx[2*c1+1];
            int i = idx[2*c2], j = idx[2*c2+1];
            double v = 0.0;
            if (m == i) v += lambda * (J - 1.0) * J * FTFinv(j, n);
            v -= lambda * (J - 1.0) * J *
                 (FFTFInv(m, j) * FFTFInv(i, n) + FFTFInvFT(m, i) * FTFinv(j, n));
            v += 0.5 * lambda * (2.0 * J - 1.0) * J *
                 (FFTFInv(i, j) * FFTFInv(m, n) + FFTFInv(i, j) * FFTFInv(m, n));
            dPdF(c1, c2) = v;
        }
    }
    dPdF += 2.0 * mu * (Mat66::Identity() - dRdF);
}

// Shape-function gradients — compute once per triangle, share between gradient and hessian
ShapeGrads shape_function_gradients(const Mat22& Dm_inv) {
    ShapeGrads grads;
    grads[1] = Dm_inv.row(0).transpose();
    grads[2] = Dm_inv.row(1).transpose();
    grads[0] = -grads[1] - grads[2];
    return grads;
}

// Cached corotated energy
double corotated_energy(double ref_area, const Mat22& Dm_inv, const TriangleDef& def, double mu, double lambda) {
    const Mat32 F = Ds(def) * Dm_inv;
    const CorotatedCache32 cache = buildCorotatedCache(F);
    return ref_area * PsiCorotated32(cache, F, mu, lambda);
}

// Single-node gradient: takes pre-computed P and gradN
Vec3 corotated_node_gradient(const Mat32& P, double ref_area, const ShapeGrads& gradN, int node) {
    Vec3 g = Vec3::Zero();
    for (int gamma = 0; gamma < 3; ++gamma) {
        double val = 0.0;
        for (int beta = 0; beta < 2; ++beta)
            val += P(gamma, beta) * gradN[node](beta);
        g(gamma) = ref_area * val;
    }
    return g;
}

// Single-node hessian row: takes pre-computed dPdF and gradN
Mat39 corotated_node_hessian(const Mat66& dPdF, double ref_area, const ShapeGrads& gradN, int node) {
    Mat39 H_row = Mat39::Zero();
    for (int j = 0; j < 3; ++j) {
        for (int gamma = 0; gamma < 3; ++gamma) {
            for (int delta = 0; delta < 3; ++delta) {
                double value = 0.0;
                for (int beta = 0; beta < 2; ++beta)
                    for (int eta = 0; eta < 2; ++eta)
                        value += dPdF(flatF(gamma, beta), flatF(delta, eta))
                                 * gradN[node](beta) * gradN[j](eta);
                H_row(gamma, 3 * j + delta) = ref_area * value;
            }
        }
    }
    return H_row;
}
// ===== END corotated_energy.cpp =====

// ===== BEGIN barrier_energy.cpp =====

#include <cmath>
#include <stdexcept>


//  t = ((q - a) · (b - a)) / ||b - a||^2
//  q = a + t (b - a)
//  t in [0, 1]
double segment_parameter_from_closest_point(const Vec3& q, const Vec3& a, const Vec3& b){
    double denom = 0.0;
    double numer = 0.0;
    for (int k = 0; k < 3; ++k) {
        const double ab_k = b(k) - a(k);
        denom += ab_k * ab_k;
        numer += (q(k) - a(k)) * ab_k;
    }

    if (denom <= 0.0) {
        return 0.0;
    }

    return clamp_scalar(numer / denom, 0.0, 1.0);
}

//  eps_{ijk} = (i-j)(j-k)(k-i) / 2
double levi_civita(int i, int j, int k){
    return 0.5 * (i - j) * (j - k) * (k - i);
}

//  b(delta) = -(delta - d_hat)^2 log(delta / d_hat)
//  b(delta) = 0  for delta >= d_hat
double scalar_barrier(double delta, double d_hat){
    if (d_hat <= 0.0) throw std::runtime_error("scalar_barrier: d_hat must be positive.");
    if (delta >= d_hat) return 0.0;
    if (delta <= 0.0) throw std::runtime_error("scalar_barrier: delta must be positive.");

    const double s = delta - d_hat;
    return -(s * s) * std::log(delta / d_hat);
}

//  b'(delta) = -2 (delta - d_hat) log(delta / d_hat) - (delta - d_hat)^2 / delta
double scalar_barrier_gradient(double delta, double d_hat){
    if (d_hat <= 0.0) throw std::runtime_error("scalar_barrier_gradient: d_hat must be positive.");
    if (delta >= d_hat) return 0.0;
    if (delta <= 0.0) throw std::runtime_error("scalar_barrier_gradient: delta must be positive.");

    const double s = delta - d_hat;
    return -2.0 * s * std::log(delta / d_hat) - (s * s) / delta;
}

// b''(delta) = d_hat^2 / delta^2 + 2 d_hat / delta - 3 - 2 log(delta / d_hat)
double scalar_barrier_hessian(double delta, double d_hat){
    if (d_hat <= 0.0) throw std::runtime_error("scalar_barrier_hessian: d_hat must be positive.");
    if (delta >= d_hat) return 0.0;
    if (delta <= 0.0) throw std::runtime_error("scalar_barrier_hessian: delta must be positive.");

    const double ratio = d_hat / delta;
    return ratio * ratio + 2.0 * ratio - 3.0 - 2.0 * std::log(delta / d_hat);
}

// E = b(delta), delta = node_triangle_distance(x, x1, x2, x3)
double node_triangle_barrier(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double d_hat, double eps){
    const NodeTriangleDistanceResult dr = node_triangle_distance(x, x1, x2, x3, eps);
    return scalar_barrier(dr.distance, d_hat);
}

// Single-DOF gradient: returns dE/d(y_dof). dof: 0=x, 1=x1, 2=x2, 3=x3
Vec3 node_triangle_barrier_gradient(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double d_hat, int dof, double eps){
    const NodeTriangleDistanceResult dr = node_triangle_distance(x, x1, x2, x3, eps);
    const double delta = dr.distance;
    const double bp    = scalar_barrier_gradient(delta, d_hat);

    Vec3 g = Vec3::Zero();
    if (bp == 0.0) return g;
    if (delta <= 0.0) throw std::runtime_error("node_triangle_barrier_gradient: distance must be positive.");

    double u[3];
    for (int k = 0; k < 3; ++k) u[k] = (x(k) - dr.closest_point(k)) / delta;

    double coeff[4] = {0.0, 0.0, 0.0, 0.0};
    double face_n[3] = {0.0, 0.0, 0.0};
    bool use_normal = false;

    switch (dr.region) {
        case NodeTriangleRegion::FaceInterior:
        {
            const double phi = dr.phi;
            const double sphi = (phi > 0.0) ? 1.0 : (phi < 0.0) ? -1.0 : 0.0;
            coeff[0] =  bp * sphi;
            coeff[1] = -bp * sphi * dr.barycentric_tilde_x[0];
            coeff[2] = -bp * sphi * dr.barycentric_tilde_x[1];
            coeff[3] = -bp * sphi * dr.barycentric_tilde_x[2];
            for (int k = 0; k < 3; ++k) face_n[k] = dr.normal(k);
            use_normal = true;
            break;
        }
        case NodeTriangleRegion::Edge12:
        {
            const double t = segment_parameter_from_closest_point(dr.closest_point, x1, x2);
            coeff[0] =  bp; coeff[1] = -bp*(1.0-t); coeff[2] = -bp*t; coeff[3] = 0.0;
            break;
        }
        case NodeTriangleRegion::Edge23:
        {
            const double t = segment_parameter_from_closest_point(dr.closest_point, x2, x3);
            coeff[0] = bp; coeff[1] = 0.0; coeff[2] = -bp*(1.0-t); coeff[3] = -bp*t;
            break;
        }
        case NodeTriangleRegion::Edge31:
        {
            const double t = segment_parameter_from_closest_point(dr.closest_point, x3, x1);
            coeff[0] = bp; coeff[1] = -bp*t; coeff[2] = 0.0; coeff[3] = -bp*(1.0-t);
            break;
        }
        case NodeTriangleRegion::Vertex1:
            coeff[0] = bp; coeff[1] = -bp; coeff[2] = 0.0; coeff[3] = 0.0; break;
        case NodeTriangleRegion::Vertex2:
            coeff[0] = bp; coeff[1] = 0.0; coeff[2] = -bp; coeff[3] = 0.0; break;
        case NodeTriangleRegion::Vertex3:
            coeff[0] = bp; coeff[1] = 0.0; coeff[2] = 0.0; coeff[3] = -bp; break;
        case NodeTriangleRegion::DegenerateTriangle:
        {
            coeff[0] = bp;
            double d1=0,d2=0,d3=0;
            for (int k=0;k<3;++k){
                double v1=dr.closest_point(k)-x1(k); d1+=v1*v1;
                double v2=dr.closest_point(k)-x2(k); d2+=v2*v2;
                double v3=dr.closest_point(k)-x3(k); d3+=v3*v3;
            }
            if (std::sqrt(d1)<=std::sqrt(d2)&&std::sqrt(d1)<=std::sqrt(d3)) coeff[1]=-bp;
            else if (std::sqrt(d2)<=std::sqrt(d3)) coeff[2]=-bp;
            else coeff[3]=-bp;
            break;
        }
    }

    if (use_normal) { for (int k=0;k<3;++k) g(k)=coeff[dof]*face_n[k]; }
    else            { for (int k=0;k<3;++k) g(k)=coeff[dof]*u[k]; }
    return g;
}

// Single-DOF hessian row: returns 3x12 block d^2E/(d(y_dof) d(y_all)). dof: 0=x,1=x1,2=x2,3=x3
Mat312 node_triangle_barrier_hessian(const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3, double d_hat, int dof, double eps){
    Mat312 H_row = Mat312::Zero();

    const NodeTriangleDistanceResult dr = node_triangle_distance(x, x1, x2, x3, eps);
    const double delta = dr.distance;
    const double bp  = scalar_barrier_gradient(delta, d_hat);
    const double bpp = scalar_barrier_hessian(delta, d_hat);

    if (bp == 0.0 && bpp == 0.0) return H_row;
    if (delta <= 0.0) throw std::runtime_error("node_triangle_barrier_hessian: distance must be positive.");

    const Vec3* Y[4] = {&x, &x1, &x2, &x3};
    const int p = dof;

    switch (dr.region) {

        // ===============================================================
        //  Cases 5-7: vertex
        //
        //  q = x_a,  r = x - x_a,  delta = ||r||,  u_i = r_i / delta
        //
        //  s_p = { +1 if p == x,  -1 if p == a,  0 otherwise }
        //
        //  H_{pk,ql} = s_p * s_q * [ b'' * u_k * u_l
        //                           + (b'/delta) * (delta_{kl} - u_k * u_l) ]
        // ===============================================================
        case NodeTriangleRegion::Vertex1:
        case NodeTriangleRegion::Vertex2:
        case NodeTriangleRegion::Vertex3:
        {
            int a_idx;
            if      (dr.region == NodeTriangleRegion::Vertex1) a_idx = 1;
            else if (dr.region == NodeTriangleRegion::Vertex2) a_idx = 2;
            else                                               a_idx = 3;

            double sp[4] = {0.0, 0.0, 0.0, 0.0};
            sp[0] = 1.0; sp[a_idx] = -1.0;

            if (sp[p] == 0.0) break;

            double u[3];
            for (int k = 0; k < 3; ++k) u[k] = (x(k) - (*Y[a_idx])(k)) / delta;

            const double c1 = bpp;
            const double c2 = bp / delta;

            for (int q = 0; q < 4; ++q) {
                if (sp[q] == 0.0) continue;
                const double sq = sp[p] * sp[q];
                for (int k = 0; k < 3; ++k) {
                    for (int l = 0; l < 3; ++l) {
                        double dkl = (k == l) ? 1.0 : 0.0;
                        H_row(k, 3*q+l) = sq * (c1 * u[k] * u[l] + c2 * (dkl - u[k] * u[l]));
                    }
                }
            }
            break;
        }

            // ===============================================================
            //  Cases 2-4: edge interior
            //
            //  Edge (x_a, x_b), inactive vertex x_c.
            //  e_i = (x_b)_i - (x_a)_i
            //  w_i = x_i - (x_a)_i
            //  alpha = w_i e_i,  beta = e_i e_i,  t = alpha / beta
            //  q_i = (x_a)_i + t * e_i
            //  r_i = x_i - q_i,  delta = ||r||,  u_i = r_i / delta
            //
            //  omega_p: dw_i/dy_{pk} = omega_p * delta_{ik}
            //    omega = { +1 for x, -1 for a, 0 for b,c }
            //
            //  epsilon_p: de_i/dy_{pk} = epsilon_p * delta_{ik}
            //    epsilon = { -1 for a, +1 for b, 0 for x,c }
            // ===============================================================
        case NodeTriangleRegion::Edge12:
        case NodeTriangleRegion::Edge23:
        case NodeTriangleRegion::Edge31:
        {
            int a_idx, b_idx, c_idx;
            if      (dr.region == NodeTriangleRegion::Edge12) { a_idx = 1; b_idx = 2; c_idx = 3; }
            else if (dr.region == NodeTriangleRegion::Edge23) { a_idx = 2; b_idx = 3; c_idx = 1; }
            else                                              { a_idx = 3; b_idx = 1; c_idx = 2; }

            // omega_p and epsilon_p for p = 0(x), 1(x1), 2(x2), 3(x3)
            double omega[4]   = {0.0, 0.0, 0.0, 0.0};
            double epsilon[4] = {0.0, 0.0, 0.0, 0.0};
            omega[0] = 1.0;     omega[a_idx] = -1.0;
            epsilon[a_idx] = -1.0;  epsilon[b_idx] = 1.0;

            const Vec3& xa = *Y[a_idx];
            const Vec3& xb = *Y[b_idx];

            // e_i, w_i
            double e[3], w[3];
            for (int i = 0; i < 3; ++i) {
                e[i] = xb(i) - xa(i);
                w[i] = x(i)  - xa(i);
            }

            // alpha = w_i e_i, beta = e_i e_i
            double alpha = 0.0, beta = 0.0;
            for (int i = 0; i < 3; ++i) { alpha += w[i]*e[i]; beta += e[i]*e[i]; }

            double t = alpha / beta;

            // r_i, u_i
            double r[3], u[3];
            for (int i = 0; i < 3; ++i) {
                r[i] = x(i) - (xa(i) + t * e[i]);
                u[i] = r[i] / delta;
            }

            // --- first derivatives ---
            // alpha_{,pk} = omega_p * e_k + epsilon_p * w_k
            // beta_{,pk}  = 2 * epsilon_p * e_k
            // t_{,pk}     = alpha_{,pk}/beta - alpha*beta_{,pk}/beta^2

            // q_{i,pk} = delta_{p,a}*delta_{ik} + t_{,pk}*e_i + t*epsilon_p*delta_{ik}
            // r_{i,pk} = delta_{p,x}*delta_{ik} - q_{i,pk}

            // Precompute t_{,pk} and r_{i,pk} for all (p,k)
            double t_d[4][3];       // t_{,pk}
            double r_d[4][3][3];    // r_{i,pk}
            double q_d[4][3][3];    // q_{i,pk}

            for (int p = 0; p < 4; ++p) {
                for (int k = 0; k < 3; ++k) {
                    double alpha_pk = omega[p] * e[k] + epsilon[p] * w[k];
                    double beta_pk  = 2.0 * epsilon[p] * e[k];
                    t_d[p][k] = alpha_pk / beta - alpha * beta_pk / (beta * beta);

                    for (int i = 0; i < 3; ++i) {
                        double dik = (i == k) ? 1.0 : 0.0;
                        double dpa = (p == a_idx) ? 1.0 : 0.0;
                        double dpx = (p == 0) ? 1.0 : 0.0;
                        q_d[p][k][i] = dpa * dik + t_d[p][k] * e[i] + t * epsilon[p] * dik;
                        r_d[p][k][i] = dpx * dik - q_d[p][k][i];
                    }
                }
            }

            // --- second derivatives ---
            // alpha_{,pk,ql} = omega_p*epsilon_q*delta_{kl} + omega_q*epsilon_p*delta_{kl}
            // beta_{,pk,ql}  = 2*epsilon_p*epsilon_q*delta_{kl}

            // t_{,pk,ql} = alpha_{,pk,ql}/beta
            //            - (alpha_{,pk}*beta_{,ql} + alpha_{,ql}*beta_{,pk} + alpha*beta_{,pk,ql}) / beta^2
            //            + 2*alpha*beta_{,pk}*beta_{,ql} / beta^3

            // q_{i,pk,ql} = t_{,pk,ql}*e_i + t_{,pk}*epsilon_q*delta_{il} + t_{,ql}*epsilon_p*delta_{ik}
            // r_{i,pk,ql} = -q_{i,pk,ql}

            // d^2 delta / dy_{pk} dy_{ql}
            //   = (1/delta) * (delta_{ij} - u_i*u_j) * r_{i,pk} * r_{j,ql}
            //     - u_i * q_{i,pk,ql}

            // H_{pk,ql} = b'' * (u_i r_{i,pk}) * (u_j r_{j,ql})
            //           + b' * d^2 delta / dy_{pk} dy_{ql}

            for (int k = 0; k < 3; ++k) {
                for (int q = 0; q < 4; ++q) {
                    for (int l = 0; l < 3; ++l) {

                        double dkl = (k == l) ? 1.0 : 0.0;

                        // alpha second derivatives
                        double alpha_pk = omega[p]*e[k] + epsilon[p]*w[k];
                        double alpha_ql = omega[q]*e[l] + epsilon[q]*w[l];
                        double alpha_pkql = (omega[p]*epsilon[q] + omega[q]*epsilon[p]) * dkl;

                        double beta_pk = 2.0*epsilon[p]*e[k];
                        double beta_ql = 2.0*epsilon[q]*e[l];
                        double beta_pkql = 2.0*epsilon[p]*epsilon[q]*dkl;

                        // t second derivative
                        double t_pkql = alpha_pkql / beta
                                        - (alpha_pk*beta_ql + alpha_ql*beta_pk + alpha*beta_pkql) / (beta*beta)
                                        + 2.0*alpha*beta_pk*beta_ql / (beta*beta*beta);

                        // q_{i,pk,ql} and sum for Hessian
                        double ddelta_pk = 0.0;  // u_i * r_{i,pk}
                        double ddelta_ql = 0.0;  // u_j * r_{j,ql}
                        for (int i = 0; i < 3; ++i) {
                            ddelta_pk += u[i] * r_d[p][k][i];
                            ddelta_ql += u[i] * r_d[q][l][i];
                        }

                        // (1/delta)*(delta_{ij}-u_i*u_j)*r_{i,pk}*r_{j,ql}
                        double proj_term = 0.0;
                        for (int i = 0; i < 3; ++i) {
                            for (int j = 0; j < 3; ++j) {
                                double dij = (i == j) ? 1.0 : 0.0;
                                proj_term += (dij - u[i]*u[j]) * r_d[p][k][i] * r_d[q][l][j];
                            }
                        }
                        proj_term /= delta;

                        // -u_i * q_{i,pk,ql}
                        double uq_term = 0.0;
                        for (int i = 0; i < 3; ++i) {
                            double dik = (i == k) ? 1.0 : 0.0;
                            double dil = (i == l) ? 1.0 : 0.0;
                            double q_ipkql = t_pkql * e[i]
                                             + t_d[p][k] * epsilon[q] * dil
                                             + t_d[q][l] * epsilon[p] * dik;
                            uq_term += u[i] * q_ipkql;
                        }

                        double d2delta = proj_term - uq_term;

                        H_row(k, 3*q+l) = bpp * ddelta_pk * ddelta_ql + bp * d2delta;
                    }
                }
            }
            break;
        }

            // ===============================================================
            //  Case 1: face interior
            //
            //  a_i = (x2)_i - (x1)_i,   b_i = (x3)_i - (x1)_i
            //  N_i = eps_{imn} a_m b_n,  eta = ||N||, n_i = N_i / eta
            //  w_i = x_i - (x1)_i
            //  psi = N_i w_i,  phi = psi / eta,  delta = |phi|,  s = sign(phi)
            //
            //  sigma^(a)_p: da_i/dy_{pk} = sigma^(a)_p * delta_{ik}
            //    { -1 for x1, +1 for x2, 0 for x,x3 }
            //
            //  sigma^(b)_p: db_i/dy_{pk} = sigma^(b)_p * delta_{ik}
            //    { -1 for x1, +1 for x3, 0 for x,x2 }
            //
            //  sigma^(w)_p: dw_i/dy_{pk} = sigma^(w)_p * delta_{ik}
            //    { +1 for x, -1 for x1, 0 for x2,x3 }
            //
            //  H_{pk,ql} = b'' * phi_{,pk} * phi_{,ql} + s * b' * phi_{,pk,ql}
            // ===============================================================
        case NodeTriangleRegion::FaceInterior:
        {
            // sigma coefficients for p = 0(x), 1(x1), 2(x2), 3(x3)
            double sig_a[4] = { 0.0, -1.0,  1.0,  0.0};  // da/dy_p
            double sig_b[4] = { 0.0, -1.0,  0.0,  1.0};  // db/dy_p
            double sig_w[4] = { 1.0, -1.0,  0.0,  0.0};  // dw/dy_p

            // a_i, b_i, w_i
            double a[3], b[3], w[3];
            for (int i = 0; i < 3; ++i) {
                a[i] = x2(i) - x1(i);
                b[i] = x3(i) - x1(i);
                w[i] = x(i)  - x1(i);
            }

            // N_i = eps_{imn} a_m b_n
            double N[3] = {0.0, 0.0, 0.0};
            for (int i = 0; i < 3; ++i)
                for (int m = 0; m < 3; ++m)
                    for (int n = 0; n < 3; ++n)
                        N[i] += levi_civita(i, m, n) * a[m] * b[n];

            // eta = ||N||
            double eta = 0.0;
            for (int i = 0; i < 3; ++i) eta += N[i] * N[i];
            eta = std::sqrt(eta);

            // n_i = N_i / eta
            double n[3];
            for (int i = 0; i < 3; ++i) n[i] = N[i] / eta;

            // psi = N_i w_i
            double psi = 0.0;
            for (int i = 0; i < 3; ++i) psi += N[i] * w[i];

            // phi = psi / eta
            double phi = psi / eta;

            // s = sign(phi)
            double s;
            if      (phi > 0.0) s =  1.0;
            else if (phi < 0.0) s = -1.0;
            else                s =  0.0;

            // --- Precompute N_{i,pk} for all (p,k) ---
            // N_{i,pk} = eps_{imn} (sig_a_p * delta_{mk} * b_n + a_m * sig_b_p * delta_{nk})
            //          = eps_{imn} * sig_a_p * delta_{mk} * b_n + eps_{imn} * a_m * sig_b_p * delta_{nk}
            //          = sig_a_p * eps_{ikn} * b_n + sig_b_p * eps_{imk} * a_m
            double Nd[4][3][3];  // Nd[p][k][i] = N_{i,pk}
            for (int p = 0; p < 4; ++p) {
                for (int k = 0; k < 3; ++k) {
                    for (int i = 0; i < 3; ++i) {
                        double val = 0.0;
                        for (int n = 0; n < 3; ++n)
                            val += sig_a[p] * levi_civita(i, k, n) * b[n];
                        for (int m = 0; m < 3; ++m)
                            val += sig_b[p] * levi_civita(i, m, k) * a[m];
                        Nd[p][k][i] = val;
                    }
                }
            }

            // --- Precompute eta_{,pk}, psi_{,pk}, phi_{,pk} ---
            double eta_d[4][3];
            double psi_d[4][3];
            double phi_d[4][3];

            for (int p = 0; p < 4; ++p) {
                for (int k = 0; k < 3; ++k) {
                    // eta_{,pk} = n_i * N_{i,pk}
                    double eta_pk = 0.0;
                    for (int i = 0; i < 3; ++i) eta_pk += n[i] * Nd[p][k][i];
                    eta_d[p][k] = eta_pk;

                    // psi_{,pk} = N_{i,pk} * w_i + N_i * sig_w_p * delta_{ik}
                    //           = N_{i,pk} * w_i + sig_w_p * N_k
                    double psi_pk = 0.0;
                    for (int i = 0; i < 3; ++i) psi_pk += Nd[p][k][i] * w[i];
                    psi_pk += sig_w[p] * N[k];
                    psi_d[p][k] = psi_pk;

                    // phi_{,pk} = psi_{,pk}/eta - psi*eta_{,pk}/eta^2
                    phi_d[p][k] = psi_pk / eta - psi * eta_pk / (eta * eta);
                }
            }

            // --- Compute H_{pk,ql} = b'' * phi_{,pk} * phi_{,ql} + s * b' * phi_{,pk,ql} ---
            for (int k = 0; k < 3; ++k) {
                for (int q = 0; q < 4; ++q) {
                    for (int l = 0; l < 3; ++l) {

                        double dkl = (k == l) ? 1.0 : 0.0;

                        double coeff_N2 = sig_a[p] * sig_b[q] - sig_a[q] * sig_b[p];

                        double nN2 = 0.0;
                        for (int i = 0; i < 3; ++i)
                            nN2 += n[i] * coeff_N2 * levi_civita(i, k, l);

                        double proj_NN = 0.0;
                        for (int i = 0; i < 3; ++i)
                            for (int j = 0; j < 3; ++j) {
                                double dij = (i == j) ? 1.0 : 0.0;
                                proj_NN += (dij - n[i]*n[j]) * Nd[p][k][i] * Nd[q][l][j];
                            }

                        double eta_pkql = nN2 + proj_NN / eta;

                        double psi_pkql = 0.0;
                        for (int i = 0; i < 3; ++i)
                            psi_pkql += coeff_N2 * levi_civita(i, k, l) * w[i];
                        psi_pkql += sig_w[q] * Nd[p][k][l];
                        psi_pkql += sig_w[p] * Nd[q][l][k];

                        double phi_pkql = psi_pkql / eta - (psi_d[p][k]*eta_d[q][l] + psi_d[q][l]*eta_d[p][k] + psi*eta_pkql) / (eta*eta)
                                          + 2.0*psi*eta_d[p][k]*eta_d[q][l] / (eta*eta*eta);

                        H_row(k, 3*q+l) = bpp * phi_d[p][k] * phi_d[q][l] + s * bp * phi_pkql;
                    }
                }
            }
            break;
        }

        case NodeTriangleRegion::DegenerateTriangle:
            break;
    }

    return H_row;
}

// =====================================================================
//  Segment--segment barrier
// =====================================================================

// E = b(delta), delta = segment_segment_distance(x1, x2, x3, x4)
double segment_segment_barrier(const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4, double d_hat, double eps){
    const auto dr = segment_segment_distance(x1, x2, x3, x4, eps);
    return scalar_barrier(dr.distance, d_hat);
}

// Single-DOF gradient: returns dE/d(y_dof). dof: 0=x1,1=x2,2=x3,3=x4
Vec3 segment_segment_barrier_gradient(const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4, double d_hat, int dof, double eps){
    const SegmentSegmentDistanceResult dr = segment_segment_distance(x1, x2, x3, x4, eps);
    const double delta = dr.distance;
    const double bp    = scalar_barrier_gradient(delta, d_hat);

    Vec3 g = Vec3::Zero();
    if (bp == 0.0) return g;
    if (delta <= 0.0) throw std::runtime_error("segment_segment_barrier_gradient: distance must be positive.");

    const Vec3 r = dr.closest_point_1 - dr.closest_point_2;
    double u[3];
    for (int k = 0; k < 3; ++k) u[k] = r(k) / delta;

    const double s = dr.s;
    const double t = dr.t;
    double mu[4] = {0.0, 0.0, 0.0, 0.0};

    switch (dr.region) {
        case SegmentSegmentRegion::Interior:
            mu[0]=bp*(1.0-s); mu[1]=bp*s; mu[2]=-bp*(1.0-t); mu[3]=-bp*t; break;
        case SegmentSegmentRegion::Edge_s0:
            mu[0]=bp; mu[1]=0.0; mu[2]=-bp*(1.0-t); mu[3]=-bp*t; break;
        case SegmentSegmentRegion::Edge_s1:
            mu[0]=0.0; mu[1]=bp; mu[2]=-bp*(1.0-t); mu[3]=-bp*t; break;
        case SegmentSegmentRegion::Edge_t0:
            mu[0]=bp*(1.0-s); mu[1]=bp*s; mu[2]=-bp; mu[3]=0.0; break;
        case SegmentSegmentRegion::Edge_t1:
            mu[0]=bp*(1.0-s); mu[1]=bp*s; mu[2]=0.0; mu[3]=-bp; break;
        case SegmentSegmentRegion::Corner_s0t0:
            mu[0]=bp; mu[1]=0.0; mu[2]=-bp; mu[3]=0.0; break;
        case SegmentSegmentRegion::Corner_s0t1:
            mu[0]=bp; mu[1]=0.0; mu[2]=0.0; mu[3]=-bp; break;
        case SegmentSegmentRegion::Corner_s1t0:
            mu[0]=0.0; mu[1]=bp; mu[2]=-bp; mu[3]=0.0; break;
        case SegmentSegmentRegion::Corner_s1t1:
            mu[0]=0.0; mu[1]=bp; mu[2]=0.0; mu[3]=-bp; break;
        case SegmentSegmentRegion::ParallelSegments:
        {
            const double muf[4] = {1.0-s, s, -(1.0-t), -t};
            for (int k=0;k<3;++k) g(k) = bp * muf[dof] * u[k];
            return g;
        }
    }
    for (int k=0;k<3;++k) g(k) = mu[dof] * u[k];
    return g;
}

// Single-DOF hessian row: returns 3x12 block. dof: 0=x1,1=x2,2=x3,3=x4
Mat312 segment_segment_barrier_hessian(const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4, double d_hat, int dof, double eps){
    Mat312 H_row = Mat312::Zero();

    const SegmentSegmentDistanceResult dr = segment_segment_distance(x1, x2, x3, x4, eps);
    const double delta = dr.distance;
    const double bp    = scalar_barrier_gradient(delta, d_hat);
    const double bpp   = scalar_barrier_hessian(delta, d_hat);

    if (bp == 0.0 && bpp == 0.0) return H_row;
    if (delta <= 0.0) throw std::runtime_error("segment_segment_barrier_hessian: distance must be positive.");

    const Vec3* Y[4] = {&x1, &x2, &x3, &x4};
    const int p = dof;

    switch (dr.region) {

        // ===============================================================
        //  Cases 6-9: vertex-vertex
        //  Same structure as node-triangle vertex cases.
        // ===============================================================
        case SegmentSegmentRegion::Corner_s0t0:
        case SegmentSegmentRegion::Corner_s0t1:
        case SegmentSegmentRegion::Corner_s1t0:
        case SegmentSegmentRegion::Corner_s1t1:
        {
            int a_idx, b_idx;
            if      (dr.region == SegmentSegmentRegion::Corner_s0t0) { a_idx = 0; b_idx = 2; }
            else if (dr.region == SegmentSegmentRegion::Corner_s0t1) { a_idx = 0; b_idx = 3; }
            else if (dr.region == SegmentSegmentRegion::Corner_s1t0) { a_idx = 1; b_idx = 2; }
            else                                                      { a_idx = 1; b_idx = 3; }

            double sp[4] = {0.0, 0.0, 0.0, 0.0};
            sp[a_idx] = 1.0; sp[b_idx] = -1.0;

            double u[3];
            for (int k = 0; k < 3; ++k) u[k] = ((*Y[a_idx])(k) - (*Y[b_idx])(k)) / delta;

            const double c1 = bpp;
            const double c2 = bp / delta;

            if (sp[p] == 0.0) break;

            for (int q = 0; q < 4; ++q) {
                const double sq = sp[p] * sp[q];
                if (sq == 0.0) continue;
                for (int k = 0; k < 3; ++k) {
                    for (int l = 0; l < 3; ++l) {
                        double dkl = (k == l) ? 1.0 : 0.0;
                        H_row(k, 3*q+l) = sq * (c1 * u[k] * u[l] + c2 * (dkl - u[k] * u[l]));
                    }
                }
            }
            break;
        }

            // ===============================================================
            //  Cases 2-5: point-segment
            //  One parameter clamped. Reduces to node-triangle edge-interior Hessian.
            // ===============================================================
        case SegmentSegmentRegion::Edge_s0:
        case SegmentSegmentRegion::Edge_s1:
        case SegmentSegmentRegion::Edge_t0:
        case SegmentSegmentRegion::Edge_t1:
        {
            // Identify the query point, edge endpoints, and inactive vertex
            int query_idx, ea_idx, eb_idx, inactive_idx;
            if      (dr.region == SegmentSegmentRegion::Edge_s0) { query_idx = 0; ea_idx = 2; eb_idx = 3; inactive_idx = 1; }
            else if (dr.region == SegmentSegmentRegion::Edge_s1) { query_idx = 1; ea_idx = 2; eb_idx = 3; inactive_idx = 0; }
            else if (dr.region == SegmentSegmentRegion::Edge_t0) { query_idx = 2; ea_idx = 0; eb_idx = 1; inactive_idx = 3; }
            else                                                  { query_idx = 3; ea_idx = 0; eb_idx = 1; inactive_idx = 2; }

            const Vec3& xq  = *Y[query_idx];
            const Vec3& xea = *Y[ea_idx];
            const Vec3& xeb = *Y[eb_idx];

            // omega_p and epsilon_p
            double omega[4]   = {0.0, 0.0, 0.0, 0.0};
            double epsilon[4] = {0.0, 0.0, 0.0, 0.0};
            omega[query_idx] = 1.0; omega[ea_idx] = -1.0;
            epsilon[ea_idx] = -1.0; epsilon[eb_idx] = 1.0;

            double e[3], w[3];
            for (int i = 0; i < 3; ++i) {
                e[i] = xeb(i) - xea(i);
                w[i] = xq(i)  - xea(i);
            }

            double alpha = 0.0, beta = 0.0;
            for (int i = 0; i < 3; ++i) { alpha += w[i]*e[i]; beta += e[i]*e[i]; }

            double t = alpha / beta;

            double r[3], u[3];
            for (int i = 0; i < 3; ++i) {
                r[i] = xq(i) - (xea(i) + t * e[i]);
                u[i] = r[i] / delta;
            }

            // Precompute t_{,pk} and r_{i,pk}, q_{i,pk}
            double t_d[4][3];
            double r_d[4][3][3];
            double q_d[4][3][3];

            for (int p = 0; p < 4; ++p) {
                for (int k = 0; k < 3; ++k) {
                    double alpha_pk = omega[p] * e[k] + epsilon[p] * w[k];
                    double beta_pk  = 2.0 * epsilon[p] * e[k];
                    t_d[p][k] = alpha_pk / beta - alpha * beta_pk / (beta * beta);

                    for (int i = 0; i < 3; ++i) {
                        double dik = (i == k) ? 1.0 : 0.0;
                        double dp_ea = (p == ea_idx) ? 1.0 : 0.0;
                        double dp_q  = (p == query_idx) ? 1.0 : 0.0;
                        q_d[p][k][i] = dp_ea * dik + t_d[p][k] * e[i] + t * epsilon[p] * dik;
                        r_d[p][k][i] = dp_q * dik - q_d[p][k][i];
                    }
                }
            }

            // Second derivatives and Hessian assembly
            for (int k = 0; k < 3; ++k) {
                for (int q = 0; q < 4; ++q) {
                    for (int l = 0; l < 3; ++l) {
                        double dkl = (k == l) ? 1.0 : 0.0;

                        double alpha_pk = omega[p]*e[k] + epsilon[p]*w[k];
                        double alpha_ql = omega[q]*e[l] + epsilon[q]*w[l];
                        double alpha_pkql = (omega[p]*epsilon[q] + omega[q]*epsilon[p]) * dkl;

                        double beta_pk = 2.0*epsilon[p]*e[k];
                        double beta_ql = 2.0*epsilon[q]*e[l];
                        double beta_pkql = 2.0*epsilon[p]*epsilon[q]*dkl;

                        double t_pkql = alpha_pkql / beta
                                        - (alpha_pk*beta_ql + alpha_ql*beta_pk + alpha*beta_pkql) / (beta*beta)
                                        + 2.0*alpha*beta_pk*beta_ql / (beta*beta*beta);

                        double ddelta_pk = 0.0, ddelta_ql = 0.0;
                        for (int i = 0; i < 3; ++i) {
                            ddelta_pk += u[i] * r_d[p][k][i];
                            ddelta_ql += u[i] * r_d[q][l][i];
                        }

                        double proj_term = 0.0;
                        for (int i = 0; i < 3; ++i) {
                            for (int j = 0; j < 3; ++j) {
                                double dij = (i == j) ? 1.0 : 0.0;
                                proj_term += (dij - u[i]*u[j]) * r_d[p][k][i] * r_d[q][l][j];
                            }
                        }
                        proj_term /= delta;

                        double uq_term = 0.0;
                        for (int i = 0; i < 3; ++i) {
                            double dik = (i == k) ? 1.0 : 0.0;
                            double dil = (i == l) ? 1.0 : 0.0;
                            double q_ipkql = t_pkql * e[i]
                                             + t_d[p][k] * epsilon[q] * dil
                                             + t_d[q][l] * epsilon[p] * dik;
                            uq_term += u[i] * q_ipkql;
                        }

                        double d2delta = proj_term - uq_term;

                        H_row(k, 3*q+l) = bpp * ddelta_pk * ddelta_ql + bp * d2delta;
                    }
                }
            }
            break;
        }

            // ===============================================================
            //  Case 1: interior
            //  Two free parameters s, t. Full differentiation through the
            //  quotient rule for s = nu/Delta, t = zeta/Delta.
            // ===============================================================
        case SegmentSegmentRegion::Interior:
        {
            // sigma coefficients for p = 0(x1), 1(x2), 2(x3), 3(x4)
            double sig_a[4] = {-1.0,  1.0,  0.0,  0.0};  // da/dy_p, a = x2-x1
            double sig_b[4] = { 0.0,  0.0, -1.0,  1.0};  // db/dy_p, b = x4-x3
            double sig_c[4] = { 1.0,  0.0, -1.0,  0.0};  // dc/dy_p, c = x1-x3

            double a[3], b[3], c[3];
            for (int i = 0; i < 3; ++i) {
                a[i] = x2(i) - x1(i);
                b[i] = x4(i) - x3(i);
                c[i] = x1(i) - x3(i);
            }

            double A = 0.0, B = 0.0, C = 0.0, D = 0.0, E = 0.0;
            for (int i = 0; i < 3; ++i) {
                A += a[i]*a[i]; B += a[i]*b[i]; C += b[i]*b[i];
                D += a[i]*c[i]; E += b[i]*c[i];
            }

            double Delta = A*C - B*B;
            double nu    = B*E - C*D;   // numerator for s
            double zeta  = A*E - B*D;   // numerator for t
            double s = nu / Delta;
            double t = zeta / Delta;

            // First derivatives of A,B,C,D,E
            double Ad[4][3], Bd[4][3], Cd[4][3], Dd[4][3], Ed[4][3];
            for (int p = 0; p < 4; ++p) {
                for (int k = 0; k < 3; ++k) {
                    Ad[p][k] = 2.0 * sig_a[p] * a[k];
                    Bd[p][k] = sig_a[p] * b[k] + sig_b[p] * a[k];
                    Cd[p][k] = 2.0 * sig_b[p] * b[k];
                    Dd[p][k] = sig_a[p] * c[k] + sig_c[p] * a[k];
                    Ed[p][k] = sig_b[p] * c[k] + sig_c[p] * b[k];
                }
            }

            // First derivatives of nu, zeta, Delta
            double nu_d[4][3], zeta_d[4][3], Delta_d[4][3];
            for (int p = 0; p < 4; ++p) {
                for (int k = 0; k < 3; ++k) {
                    nu_d[p][k]    = Bd[p][k]*E + B*Ed[p][k] - Cd[p][k]*D - C*Dd[p][k];
                    zeta_d[p][k]  = Ad[p][k]*E + A*Ed[p][k] - Bd[p][k]*D - B*Dd[p][k];
                    Delta_d[p][k] = Ad[p][k]*C + A*Cd[p][k] - 2.0*B*Bd[p][k];
                }
            }

            // s_{,pk} and t_{,pk}
            double s_d[4][3], t_d_arr[4][3];
            for (int p = 0; p < 4; ++p) {
                for (int k = 0; k < 3; ++k) {
                    s_d[p][k]     = nu_d[p][k]/Delta   - nu*Delta_d[p][k]/(Delta*Delta);
                    t_d_arr[p][k] = zeta_d[p][k]/Delta - zeta*Delta_d[p][k]/(Delta*Delta);
                }
            }

            // p_i = (x1)_i + s*a_i,  q_i = (x3)_i + t*b_i
            // p_{i,pk} = delta_{p,0}*delta_{ik} + s_{,pk}*a_i + s*sig_a_p*delta_{ik}
            // q_{i,pk} = delta_{p,2}*delta_{ik} + t_{,pk}*b_i + t*sig_b_p*delta_{ik}
            // r_{i,pk} = p_{i,pk} - q_{i,pk}
            double r_d[4][3][3];
            double p_d[4][3][3], q_d[4][3][3];

            for (int p = 0; p < 4; ++p) {
                for (int k = 0; k < 3; ++k) {
                    for (int i = 0; i < 3; ++i) {
                        double dik = (i == k) ? 1.0 : 0.0;
                        double dp0 = (p == 0) ? 1.0 : 0.0;  // x1
                        double dp2 = (p == 2) ? 1.0 : 0.0;  // x3
                        p_d[p][k][i] = dp0 * dik + s_d[p][k] * a[i] + s * sig_a[p] * dik;
                        q_d[p][k][i] = dp2 * dik + t_d_arr[p][k] * b[i] + t * sig_b[p] * dik;
                        r_d[p][k][i] = p_d[p][k][i] - q_d[p][k][i];
                    }
                }
            }

            double r_vec[3], u[3];
            for (int i = 0; i < 3; ++i) {
                r_vec[i] = (x1(i) + s*a[i]) - (x3(i) + t*b[i]);
                u[i] = r_vec[i] / delta;
            }

            // Second derivatives and Hessian
            for (int k = 0; k < 3; ++k) {
                for (int q = 0; q < 4; ++q) {
                    for (int l = 0; l < 3; ++l) {
                        double dkl = (k == l) ? 1.0 : 0.0;

                        double A_pkql = 2.0 * sig_a[p] * sig_a[q] * dkl;
                        double B_pkql = (sig_a[p]*sig_b[q] + sig_a[q]*sig_b[p]) * dkl;
                        double C_pkql = 2.0 * sig_b[p] * sig_b[q] * dkl;
                        double D_pkql = (sig_a[p]*sig_c[q] + sig_a[q]*sig_c[p]) * dkl;
                        double E_pkql = (sig_b[p]*sig_c[q] + sig_b[q]*sig_c[p]) * dkl;

                        double nu_pkql = B_pkql*E + Bd[p][k]*Ed[q][l] + Bd[q][l]*Ed[p][k] + B*E_pkql
                                         - C_pkql*D - Cd[p][k]*Dd[q][l] - Cd[q][l]*Dd[p][k] - C*D_pkql;
                        double Delta_pkql = A_pkql*C + Ad[p][k]*Cd[q][l] + Ad[q][l]*Cd[p][k] + A*C_pkql
                                            - 2.0*(Bd[p][k]*Bd[q][l] + B*B_pkql);
                        double zeta_pkql = A_pkql*E + Ad[p][k]*Ed[q][l] + Ad[q][l]*Ed[p][k] + A*E_pkql
                                           - B_pkql*D - Bd[p][k]*Dd[q][l] - Bd[q][l]*Dd[p][k] - B*D_pkql;

                        double s_pkql = nu_pkql/Delta
                                        - (nu_d[p][k]*Delta_d[q][l] + nu_d[q][l]*Delta_d[p][k] + nu*Delta_pkql)/(Delta*Delta)
                                        + 2.0*nu*Delta_d[p][k]*Delta_d[q][l]/(Delta*Delta*Delta);
                        double t_pkql = zeta_pkql/Delta
                                        - (zeta_d[p][k]*Delta_d[q][l] + zeta_d[q][l]*Delta_d[p][k] + zeta*Delta_pkql)/(Delta*Delta)
                                        + 2.0*zeta*Delta_d[p][k]*Delta_d[q][l]/(Delta*Delta*Delta);

                        double ddelta_pk = 0.0, ddelta_ql = 0.0;
                        for (int i = 0; i < 3; ++i) {
                            ddelta_pk += u[i] * r_d[p][k][i];
                            ddelta_ql += u[i] * r_d[q][l][i];
                        }

                        double proj_term = 0.0;
                        for (int i = 0; i < 3; ++i) {
                            for (int j = 0; j < 3; ++j) {
                                double dij = (i == j) ? 1.0 : 0.0;
                                proj_term += (dij - u[i]*u[j]) * r_d[p][k][i] * r_d[q][l][j];
                            }
                        }
                        proj_term /= delta;

                        double ur_term = 0.0;
                        for (int i = 0; i < 3; ++i) {
                            double dik = (i == k) ? 1.0 : 0.0;
                            double dil = (i == l) ? 1.0 : 0.0;
                            double p_ipkql = s_pkql * a[i] + s_d[p][k] * sig_a[q] * dil + s_d[q][l] * sig_a[p] * dik;
                            double q_ipkql = t_pkql * b[i] + t_d_arr[p][k] * sig_b[q] * dil + t_d_arr[q][l] * sig_b[p] * dik;
                            ur_term += u[i] * (p_ipkql - q_ipkql);
                        }

                        H_row(k, 3*q+l) = bpp * ddelta_pk * ddelta_ql + bp * (proj_term + ur_term);
                    }
                }
            }
            break;
        }

        case SegmentSegmentRegion::ParallelSegments:
            break;
    }

    return H_row;
}

// Combined NT gradient+hessian — single distance evaluation
std::pair<Vec3, Mat312> node_triangle_barrier_gradient_and_hessian(
        const Vec3& x, const Vec3& x1, const Vec3& x2, const Vec3& x3,
        double d_hat, int dof, double eps) {
    Vec3   g     = node_triangle_barrier_gradient(x, x1, x2, x3, d_hat, dof, eps);
    Mat312 H_row = node_triangle_barrier_hessian(x, x1, x2, x3, d_hat, dof, eps);
    return {g, H_row};
}

// Combined SS gradient+hessian — single distance evaluation
std::pair<Vec3, Mat312> segment_segment_barrier_gradient_and_hessian(
        const Vec3& x1, const Vec3& x2, const Vec3& x3, const Vec3& x4,
        double d_hat, int dof, double eps) {
    Vec3   g     = segment_segment_barrier_gradient(x1, x2, x3, x4, d_hat, dof, eps);
    Mat312 H_row = segment_segment_barrier_hessian(x1, x2, x3, x4, d_hat, dof, eps);
    return {g, H_row};
}
// ===== END barrier_energy.cpp =====

// ===== BEGIN physics.cpp =====
#include <algorithm>
#include <cmath>

double triangle_ref_area_2d(const RefMesh& ref_mesh, const std::vector<Vec2>& X, const Tri& tri) {
    const Vec2& X0 = X[tri.v[0]];
    const Vec2& X1 = X[tri.v[1]];
    const Vec2& X2 = X[tri.v[2]];

    Mat22 Dm_local;
    Dm_local.col(0) = X1 - X0;
    Dm_local.col(1) = X2 - X0;
    return 0.5 * std::abs(Dm_local.determinant());
}


VertexAdjacency build_vertex_adjacency(const RefMesh& ref_mesh) {
    VertexAdjacency adj;
    adj.incident_triangle_indices.resize(ref_mesh.num_positions);

    for (int t = 0; t < static_cast<int>(ref_mesh.tris.size()); ++t) {
        const Tri& tri = ref_mesh.tris[t];
        for (int a : tri.v) adj.incident_triangle_indices[a].push_back(t);
    }

    return adj;
}

double compute_incremental_potential_no_barrier(const RefMesh& ref_mesh, const std::vector<Pin>& pins,
                                                const SimParams& params, const std::vector<Vec3>& x, const std::vector<Vec3>& xhat) {
    double E = 0.0, PE = 0.0, dt2 = params.dt * params.dt;

    for (int i = 0; i < static_cast<int>(x.size()); ++i) {
        Vec3 dx = x[i] - xhat[i];
        E += 0.5 * ref_mesh.mass[i] * dx.squaredNorm();
    }

    for (int i = 0; i < static_cast<int>(x.size()); ++i)
        PE += -ref_mesh.mass[i] * params.gravity.dot(x[i]);

    for (const Pin& pin : pins) {
        Vec3 dx = x[pin.vertex_index] - pin.target_position;
        PE += 0.5 * params.kpin * dx.squaredNorm();
    }

    for (size_t t = 0; t < ref_mesh.tris.size(); ++t)
        PE += corotated_energy(ref_mesh.area[t], ref_mesh.Dm_inverse[t], make_def_triangle(x, ref_mesh.tris[t]), params.mu, params.lambda);

    return E + dt2 * PE;
}

std::pair<Vec3, Mat33> compute_local_gradient_and_hessian_no_barrier(int vi, const RefMesh& ref_mesh, const VertexAdjacency& adj, const std::vector<Pin>& pins, const SimParams& params, const std::vector<Vec3>& x, const std::vector<Vec3>& xhat){
    double dt2 = params.dt * params.dt;
    Vec3  g = Vec3::Zero();
    Mat33 H = Mat33::Zero();

    g += ref_mesh.mass[vi] * (x[vi] - xhat[vi]);
    g += dt2 * (-ref_mesh.mass[vi] * params.gravity);
    H += ref_mesh.mass[vi] * Mat33::Identity();

    for (const Pin& pin : pins) {
        if (pin.vertex_index == vi) {
            g += dt2 * params.kpin * (x[vi] - pin.target_position);
            H += dt2 * params.kpin * Mat33::Identity();
        }
    }

    for (int ti : adj.incident_triangle_indices[vi]) {
        const Tri& tri = ref_mesh.tris[ti];
        int a = -1;
        for (int j = 0; j < 3; ++j) if (tri.v[j] == vi) { a = j; break; }

        const TriangleDef def = make_def_triangle(x, tri);
        Mat32 Ds_mat;
        Ds_mat.col(0) = def.x[1] - def.x[0];
        Ds_mat.col(1) = def.x[2] - def.x[0];
        const Mat22& Dm_inv = ref_mesh.Dm_inverse[ti];
        const Mat32  F      = Ds_mat * Dm_inv;
        const double A      = ref_mesh.area[ti];

        const CorotatedCache32 cache = buildCorotatedCache(F);
        const ShapeGrads gradN = shape_function_gradients(Dm_inv);
        const Mat32 P = PCorotated32(cache, F, params.mu, params.lambda);
        Mat66 dPdF; dPdFCorotated32(cache, params.mu, params.lambda, dPdF);
        g += dt2 * corotated_node_gradient(P, A, gradN, a);
        H += dt2 * corotated_node_hessian(dPdF, A, gradN, a).template block<3, 3>(0, 3 * a);
    }

    return {g, H};
}

Vec3 compute_local_gradient_no_barrier(int vi, const RefMesh& ref_mesh, const VertexAdjacency& adj, const std::vector<Pin>& pins, const SimParams& params, const std::vector<Vec3>& x, const std::vector<Vec3>& xhat){
    double dt2 = params.dt * params.dt;
    Vec3 g = Vec3::Zero();

    g += ref_mesh.mass[vi] * (x[vi] - xhat[vi]);
    g += dt2 * (-ref_mesh.mass[vi] * params.gravity);

    for (const Pin& pin : pins) {
        if (pin.vertex_index == vi)
            g += dt2 * params.kpin * (x[vi] - pin.target_position);
    }

    for (int ti : adj.incident_triangle_indices[vi]) {
        const Tri& tri = ref_mesh.tris[ti];
        int a = -1;
        for (int j = 0; j < 3; ++j) if (tri.v[j] == vi) { a = j; break; }

        const TriangleDef def = make_def_triangle(x, tri);
        Mat32 Ds_mat;
        Ds_mat.col(0) = def.x[1] - def.x[0];
        Ds_mat.col(1) = def.x[2] - def.x[0];
        const Mat22& Dm_inv = ref_mesh.Dm_inverse[ti];
        const Mat32  F      = Ds_mat * Dm_inv;
        const double A      = ref_mesh.area[ti];

        const CorotatedCache32 cache = buildCorotatedCache(F);
        const ShapeGrads gradN = shape_function_gradients(Dm_inv);
        const Mat32 P = PCorotated32(cache, F, params.mu, params.lambda);
        g += dt2 * corotated_node_gradient(P, A, gradN, a);
    }

    return g;
}

double compute_global_residual(const RefMesh& ref_mesh, const VertexAdjacency& adj, const std::vector<Pin>& pins, const SimParams& params, const std::vector<Vec3>& x, const std::vector<Vec3>& xhat){
    double r_inf = 0.0;
    for (int i = 0; i < static_cast<int>(x.size()); ++i) {
        Vec3 g = compute_local_gradient_no_barrier(i, ref_mesh, adj, pins, params, x, xhat);
        r_inf = std::max(r_inf, g.cwiseAbs().maxCoeff());
    }
    return r_inf;
}
// ===== END physics.cpp =====

// ===== BEGIN make_shape.cpp =====
#include <unordered_map>

TriangleRest make_rest_triangle(const std::vector<Vec2>& X, const Tri& tri) {
    TriangleRest rest;
    rest.X[0] = X[tri.v[0]];
    rest.X[1] = X[tri.v[1]];
    rest.X[2] = X[tri.v[2]];
    return rest;
}

TriangleDef make_def_triangle(const std::vector<Vec3>& x, const Tri& tri) {
    TriangleDef def;
    def.x[0] = x[tri.v[0]];
    def.x[1] = x[tri.v[1]];
    def.x[2] = x[tri.v[2]];
    return def;
}

void build_xhat(std::vector<Vec3>& xhat, const std::vector<Vec3>& x, const std::vector<Vec3>& v, double dt) {
    int n = static_cast<int>(x.size());
    xhat.resize(n);
    for (int i = 0; i < n; ++i) xhat[i] = x[i] + dt * v[i];
}

void update_velocity(std::vector<Vec3>& v, const std::vector<Vec3>& xnew, const std::vector<Vec3>& xold, double dt) {
    int n = static_cast<int>(xnew.size());
    v.resize(n);
    for (int i = 0; i < n; ++i) v[i] = (xnew[i] - xold[i]) / dt;
}

void clear_model(RefMesh& ref_mesh, DeformedState& state, std::vector<Vec2>& X, std::vector<Pin>& pins) {
    X.clear();
    ref_mesh.tris.clear();
    state.deformed_positions.clear();
    state.velocities.clear();
    pins.clear();
}

int build_single_triangle(RefMesh& ref_mesh, DeformedState& state, std::vector<Vec2>& X,
                          const Vec2& X0, const Vec2& X1, const Vec2& X2,
                          const Vec3& x0, const Vec3& x1, const Vec3& x2) {
    int base = static_cast<int>(state.deformed_positions.size());

    X.push_back(X0);
    X.push_back(X1);
    X.push_back(X2);

    state.deformed_positions.push_back(x0);
    state.deformed_positions.push_back(x1);
    state.deformed_positions.push_back(x2);

    ref_mesh.tris.push_back(Tri{{base + 0, base + 1, base + 2}});
    return base;
}

void append_pin(std::vector<Pin>& pins, int vertex_index, const std::vector<Vec3>& x) {
    pins.push_back(Pin{vertex_index, x[vertex_index]});
}

// Total number of vertices is: (nx + 1) * (ny + 1) and total number of triangles is: 2 * nx * ny
int build_square_mesh(RefMesh& ref_mesh, DeformedState& state, std::vector<Vec2>& X, int nx, int ny, double width, double height, const Vec3& origin) {
    int base = static_cast<int>(state.deformed_positions.size());

    for (int j = 0; j <= ny; ++j) {
        for (int i = 0; i <= nx; ++i) {

            // Normalize grid coordinates from 0 to 1
            double u = static_cast<double>(i) / nx;
            double v = static_cast<double>(j) / ny;

            // Scale to actual size
            double x_ref = u * width;
            double y_ref = v * height;

            // Store reference (2D) and deformed (3D) positions
            X.push_back(Vec2(x_ref, y_ref));
            state.deformed_positions.push_back(origin + Vec3(x_ref, y_ref, 0.0));
        }
    }

    // convert (col, row) → vertex index
    auto vertex_index = [base, nx](int i, int j) {
        return base + j * (nx + 1) + i;
    };

    // Create triangles
    for (int j = 0; j < ny; ++j) {
        for (int i = 0; i < nx; ++i) {
            int v00 = vertex_index(i, j);
            int v10 = vertex_index(i + 1, j);
            int v01 = vertex_index(i, j + 1);
            int v11 = vertex_index(i + 1, j + 1);

            // Split square into two triangles
            ref_mesh.tris.push_back(Tri{{v00, v10, v11}});
            ref_mesh.tris.push_back(Tri{{v00, v11, v01}});
        }
    }

    ref_mesh.initialize(X);

    return base;
}

std::unordered_map<int, std::vector<int>> build_incident_triangle_map(const std::vector<int>& indices) {
    std::unordered_map<int, std::vector<int>> result;
    for (int i = 0; i < static_cast<int>(indices.size()); ++i)
        result[indices[i]].push_back(i);
    return result;
}
// ===== END make_shape.cpp =====

// ===== BEGIN solver.cpp =====

void update_one_vertex(int vi, const RefMesh& ref_mesh, const VertexAdjacency& adj,
                       const std::vector<Pin>& pins, const SimParams& params, const std::vector<Vec3>& xhat, std::vector<Vec3>& x){
    auto [g, H] = compute_local_gradient_and_hessian_no_barrier(vi, ref_mesh, adj, pins, params, x, xhat);
    Vec3 dx = matrix3d_inverse(H) * g;
    x[vi] -= params.step_weight * dx;
}

SolverResult global_gauss_seidel_solver(const RefMesh& ref_mesh, const VertexAdjacency& adj,
                                        const std::vector<Pin>& pins, const SimParams& params, std::vector<Vec3>& xnew,
                                        const std::vector<Vec3>& xhat, std::vector<double>* residual_history){
    if (residual_history) residual_history->clear();

    auto eval_residual = [&]() { return compute_global_residual(ref_mesh, adj, pins, params, xnew, xhat); };

    SolverResult result;
    result.initial_residual = eval_residual();
    result.final_residual = result.initial_residual;
    result.iterations = 0;

    if (residual_history) residual_history->push_back(result.initial_residual);
    if (result.initial_residual < params.tol_abs) return result;

    for (int iter = 1; iter <= params.max_global_iters; ++iter) {
        for (int vi = 0; vi < static_cast<int>(xnew.size()); ++vi)
            update_one_vertex(vi, ref_mesh, adj, pins, params, xhat, xnew);

        result.final_residual = eval_residual();
        result.iterations = iter;

        if (residual_history) residual_history->push_back(result.final_residual);
        if (result.final_residual < params.tol_abs) return result;
    }

    return result;
}
// ===== END solver.cpp =====

// ===== BEGIN visualization.cpp =====
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>

void export_obj(const std::string& filename, const std::vector<Vec3>& x, const std::vector<Tri>& tris) {
    std::ofstream out(filename);
    if (!out) {
        std::cerr << "Error: cannot write " << filename << "\n";
        return;
    }

    for (const auto& p : x) out << "v " << p.x() << " " << p.y() << " " << p.z() << "\n";
    for (const auto& t : tris) out << "f " << (t.v[0] + 1) << " " << (t.v[1] + 1) << " " << (t.v[2] + 1) << "\n";
}

void export_frame(const std::string& outdir, int frame, const std::vector<Vec3>& x, const std::vector<Tri>& tris) {
    std::ostringstream ss;
    ss << outdir << "/frame_" << std::setw(4) << std::setfill('0') << frame << ".obj";
    export_obj(ss.str(), x, tris);
}
// ===== END visualization.cpp =====


// ===== BEGIN sandbox-specific barrier-integrated utilities =====

struct NodeTrianglePair {
    int node{-1};
    int tri_v[3]{-1, -1, -1};
};

struct SegmentSegmentPair {
    int v[4]{-1, -1, -1, -1};
};

struct MeshPatchInfo {
    int vertex_begin{0};
    int vertex_end{0};
    int tri_begin{0};
    int tri_end{0};
};

MeshPatchInfo build_square_patch(RefMesh& ref_mesh, DeformedState& state, std::vector<Vec2>& X,
                                 int nx, int ny, double width, double height, const Vec3& origin) {
    MeshPatchInfo patch;
    patch.vertex_begin = static_cast<int>(state.deformed_positions.size());
    patch.tri_begin = static_cast<int>(ref_mesh.tris.size());
    build_square_mesh(ref_mesh, state, X, nx, ny, width, height, origin);
    patch.vertex_end = static_cast<int>(state.deformed_positions.size());
    patch.tri_end = static_cast<int>(ref_mesh.tris.size());
    return patch;
}

std::vector<std::array<int, 2>> extract_patch_edges(const RefMesh& ref_mesh, const MeshPatchInfo& patch) {
    std::set<std::pair<int, int>> unique_edges;
    for (int ti = patch.tri_begin; ti < patch.tri_end; ++ti) {
        const Tri& tri = ref_mesh.tris[ti];
        for (int e = 0; e < 3; ++e) {
            int a = tri.v[e];
            int b = tri.v[(e + 1) % 3];
            if (a > b) std::swap(a, b);
            unique_edges.insert({a, b});
        }
    }

    std::vector<std::array<int, 2>> edges;
    edges.reserve(unique_edges.size());
    for (const auto& [a, b] : unique_edges) edges.push_back({a, b});
    return edges;
}

std::vector<NodeTrianglePair> build_inter_patch_node_triangle_pairs(const RefMesh& ref_mesh,
                                                                    const MeshPatchInfo& a,
                                                                    const MeshPatchInfo& b) {
    std::vector<NodeTrianglePair> pairs;
    for (int node = a.vertex_begin; node < a.vertex_end; ++node) {
        for (int ti = b.tri_begin; ti < b.tri_end; ++ti) {
            const Tri& tri = ref_mesh.tris[ti];
            pairs.push_back(NodeTrianglePair{node, {tri.v[0], tri.v[1], tri.v[2]}});
        }
    }
    for (int node = b.vertex_begin; node < b.vertex_end; ++node) {
        for (int ti = a.tri_begin; ti < a.tri_end; ++ti) {
            const Tri& tri = ref_mesh.tris[ti];
            pairs.push_back(NodeTrianglePair{node, {tri.v[0], tri.v[1], tri.v[2]}});
        }
    }
    return pairs;
}

std::vector<SegmentSegmentPair> build_inter_patch_segment_segment_pairs(const RefMesh& ref_mesh,
                                                                        const MeshPatchInfo& a,
                                                                        const MeshPatchInfo& b) {
    const auto edges_a = extract_patch_edges(ref_mesh, a);
    const auto edges_b = extract_patch_edges(ref_mesh, b);

    std::vector<SegmentSegmentPair> pairs;
    pairs.reserve(edges_a.size() * edges_b.size());
    for (const auto& ea : edges_a) {
        for (const auto& eb : edges_b) {
            pairs.push_back(SegmentSegmentPair{{ea[0], ea[1], eb[0], eb[1]}});
        }
    }
    return pairs;
}

double compute_incremental_potential_with_barrier(const RefMesh& ref_mesh,
                                                  const std::vector<Pin>& pins,
                                                  const SimParams& params,
                                                  const std::vector<Vec3>& x,
                                                  const std::vector<Vec3>& xhat,
                                                  const std::vector<NodeTrianglePair>& nt_pairs,
                                                  const std::vector<SegmentSegmentPair>& ss_pairs) {
    double E = compute_incremental_potential_no_barrier(ref_mesh, pins, params, x, xhat);
    if (params.d_hat <= 0.0) return E;

    const double dt2 = params.dt * params.dt;
    for (const auto& p : nt_pairs) {
        E += dt2 * node_triangle_barrier(
                x[p.node], x[p.tri_v[0]], x[p.tri_v[1]], x[p.tri_v[2]], params.d_hat);
    }
    for (const auto& p : ss_pairs) {
        E += dt2 * segment_segment_barrier(
                x[p.v[0]], x[p.v[1]], x[p.v[2]], x[p.v[3]], params.d_hat);
    }
    return E;
}

std::pair<Vec3, Mat33> compute_local_gradient_and_hessian_with_barrier(
        int vi,
        const RefMesh& ref_mesh,
        const VertexAdjacency& adj,
        const std::vector<Pin>& pins,
        const SimParams& params,
        const std::vector<Vec3>& x,
        const std::vector<Vec3>& xhat,
        const std::vector<NodeTrianglePair>& nt_pairs,
        const std::vector<SegmentSegmentPair>& ss_pairs) {
    auto [g, H] = compute_local_gradient_and_hessian_no_barrier(vi, ref_mesh, adj, pins, params, x, xhat);
    if (params.d_hat <= 0.0) return {g, H};

    const double dt2 = params.dt * params.dt;

    for (const auto& p : nt_pairs) {
        int dof = -1;
        if      (vi == p.node)      dof = 0;
        else if (vi == p.tri_v[0])  dof = 1;
        else if (vi == p.tri_v[1])  dof = 2;
        else if (vi == p.tri_v[2])  dof = 3;
        if (dof < 0) continue;
        auto [bg, bH] = node_triangle_barrier_gradient_and_hessian(
                x[p.node], x[p.tri_v[0]], x[p.tri_v[1]], x[p.tri_v[2]], params.d_hat, dof);
        g += dt2 * bg;
        H += dt2 * bH.block<3, 3>(0, 3 * dof);
    }

    for (const auto& p : ss_pairs) {
        int dof = -1;
        if      (vi == p.v[0]) dof = 0;
        else if (vi == p.v[1]) dof = 1;
        else if (vi == p.v[2]) dof = 2;
        else if (vi == p.v[3]) dof = 3;
        if (dof < 0) continue;
        auto [bg, bH] = segment_segment_barrier_gradient_and_hessian(
                x[p.v[0]], x[p.v[1]], x[p.v[2]], x[p.v[3]], params.d_hat, dof);
        g += dt2 * bg;
        H += dt2 * bH.block<3, 3>(0, 3 * dof);
    }

    return {g, H};
}

Vec3 compute_local_gradient_with_barrier(
        int vi,
        const RefMesh& ref_mesh,
        const VertexAdjacency& adj,
        const std::vector<Pin>& pins,
        const SimParams& params,
        const std::vector<Vec3>& x,
        const std::vector<Vec3>& xhat,
        const std::vector<NodeTrianglePair>& nt_pairs,
        const std::vector<SegmentSegmentPair>& ss_pairs) {
    auto [g, H] = compute_local_gradient_and_hessian_with_barrier(
            vi, ref_mesh, adj, pins, params, x, xhat, nt_pairs, ss_pairs);
    return g;
}

double compute_global_residual_with_barrier(
        const RefMesh& ref_mesh,
        const VertexAdjacency& adj,
        const std::vector<Pin>& pins,
        const SimParams& params,
        const std::vector<Vec3>& x,
        const std::vector<Vec3>& xhat,
        const std::vector<NodeTrianglePair>& nt_pairs,
        const std::vector<SegmentSegmentPair>& ss_pairs) {
    double r_inf = 0.0;
    for (int i = 0; i < static_cast<int>(x.size()); ++i) {
        const Vec3 g = compute_local_gradient_with_barrier(
                i, ref_mesh, adj, pins, params, x, xhat, nt_pairs, ss_pairs);
        r_inf = std::max(r_inf, std::abs(g.x()));
        r_inf = std::max(r_inf, std::abs(g.y()));
        r_inf = std::max(r_inf, std::abs(g.z()));
    }
    return r_inf;
}

void update_one_vertex_with_barrier(
        int vi,
        const RefMesh& ref_mesh,
        const VertexAdjacency& adj,
        const std::vector<Pin>& pins,
        const SimParams& params,
        const std::vector<Vec3>& xhat,
        const std::vector<NodeTrianglePair>& nt_pairs,
        const std::vector<SegmentSegmentPair>& ss_pairs,
        std::vector<Vec3>& x) {
    auto [g, H] = compute_local_gradient_and_hessian_with_barrier(
            vi, ref_mesh, adj, pins, params, x, xhat, nt_pairs, ss_pairs);
    const Vec3 dx = matrix3d_inverse(H) * g;
    x[vi] -= params.step_weight * dx;
}

SolverResult global_gauss_seidel_solver_with_barrier(
        const RefMesh& ref_mesh,
        const VertexAdjacency& adj,
        const std::vector<Pin>& pins,
        const SimParams& params,
        const std::vector<NodeTrianglePair>& nt_pairs,
        const std::vector<SegmentSegmentPair>& ss_pairs,
        std::vector<Vec3>& xnew,
        const std::vector<Vec3>& xhat,
        std::vector<double>* residual_history = nullptr) {
    if (residual_history) residual_history->clear();

    auto eval_residual = [&]() {
        return compute_global_residual_with_barrier(
                ref_mesh, adj, pins, params, xnew, xhat, nt_pairs, ss_pairs);
    };

    SolverResult result;
    result.initial_residual = eval_residual();
    result.final_residual = result.initial_residual;
    result.iterations = 0;

    if (residual_history) residual_history->push_back(result.initial_residual);
    if (result.initial_residual < params.tol_abs) return result;

    for (int iter = 1; iter <= params.max_global_iters; ++iter) {
        for (int vi = 0; vi < static_cast<int>(xnew.size()); ++vi) {
            update_one_vertex_with_barrier(
                    vi, ref_mesh, adj, pins, params, xhat, nt_pairs, ss_pairs, xnew);
        }

        result.final_residual = eval_residual();
        result.iterations = iter;
        if (residual_history) residual_history->push_back(result.final_residual);
        if (result.final_residual < params.tol_abs) return result;
    }

    return result;
}

// ===== END sandbox-specific barrier-integrated utilities =====

int main() {
    SimParams params;
    params.dt = 1.0 / 30.0;
    params.mu = 10.0;
    params.lambda = 10.0;
    params.density = 1.0;
    params.thickness = 0.1;
    params.kpin = 1e7;
    params.gravity = Vec3(0.0, -9.81, 0.0);
    params.max_global_iters = 80;
    params.tol_abs = 1e-6;
    params.step_weight = 1.0;
    params.d_hat = 0.75;

    RefMesh ref_mesh;
    DeformedState state;
    std::vector<Vec2> X;
    std::vector<Pin> pins;

    clear_model(ref_mesh, state, X, pins);

    const MeshPatchInfo patch_a = build_square_patch(ref_mesh, state, X, 2, 2, 1.5, 1.5, Vec3(-0.90, 0.00, 0.00));
    const MeshPatchInfo patch_b = build_square_patch(ref_mesh, state, X, 2, 2, 1.5, 1.5, Vec3(-0.25, 0.20, 0.45));

    state.velocities.assign(state.deformed_positions.size(), Vec3::Zero());

    // break symmetry so the contact terms are exercised immediately
    for (int i = patch_a.vertex_begin; i < patch_a.vertex_end; ++i) {
        const double t = static_cast<double>(i - patch_a.vertex_begin);
        state.deformed_positions[i] += Vec3(0.01 * std::sin(t), 0.00, 0.02 * std::cos(t));
    }
    for (int i = patch_b.vertex_begin; i < patch_b.vertex_end; ++i) {
        const double t = static_cast<double>(i - patch_b.vertex_begin);
        state.deformed_positions[i] += Vec3(-0.01 * std::cos(t), 0.00, -0.015 * std::sin(t));
    }

    // Pin the top corners of both patches.
    append_pin(pins, patch_a.vertex_begin + 6, state.deformed_positions);
    append_pin(pins, patch_a.vertex_begin + 8, state.deformed_positions);
    append_pin(pins, patch_b.vertex_begin + 6, state.deformed_positions);
    append_pin(pins, patch_b.vertex_begin + 8, state.deformed_positions);

    ref_mesh.initialize(X);
    ref_mesh.build_lumped_mass(params.density, params.thickness);
    const VertexAdjacency adj = build_vertex_adjacency(ref_mesh);

    const auto nt_pairs = build_inter_patch_node_triangle_pairs(ref_mesh, patch_a, patch_b);
    const auto ss_pairs = build_inter_patch_segment_segment_pairs(ref_mesh, patch_a, patch_b);

    std::cout << "Vertices:  " << state.deformed_positions.size() << "\n";
    std::cout << "Triangles: " << ref_mesh.tris.size() << "\n";
    std::cout << "NT pairs:  " << nt_pairs.size() << "\n";
    std::cout << "SS pairs:  " << ss_pairs.size() << "\n";

    std::string outdir = "frames_sandbox_barrier";
    if (fs::exists(outdir)) fs::remove_all(outdir);
    fs::create_directories(outdir);
    export_frame(outdir, 0, state.deformed_positions, ref_mesh.tris);

    const int num_frames = 60;
    using Clock = std::chrono::steady_clock;
    auto sim_start = Clock::now();
    double total_solver_ms = 0.0;

    for (int frame_index = 1; frame_index <= num_frames; ++frame_index) {
        std::vector<Vec3> xhat;
        build_xhat(xhat, state.deformed_positions, state.velocities, params.dt);

        std::vector<Vec3> xnew = state.deformed_positions;

        auto solver_start = Clock::now();
        const SolverResult result = global_gauss_seidel_solver_with_barrier(
                ref_mesh, adj, pins, params, nt_pairs, ss_pairs, xnew, xhat);
        auto solver_end = Clock::now();

        const double solver_ms = std::chrono::duration<double, std::milli>(solver_end - solver_start).count();
        total_solver_ms += solver_ms;

        const double total_energy = compute_incremental_potential_with_barrier(
                ref_mesh, pins, params, xnew, xhat, nt_pairs, ss_pairs);

        std::cout << "Frame " << std::setw(4) << frame_index
                  << " | initial_residual = " << std::scientific << result.initial_residual
                  << " | final_residual = " << std::scientific << result.final_residual
                  << " | global_iters = " << std::setw(3) << result.iterations
                  << " | energy = " << std::scientific << total_energy
                  << " | solver_time = " << std::fixed << std::setprecision(3) << solver_ms << " ms\n";

        update_velocity(state.velocities, xnew, state.deformed_positions, params.dt);
        state.deformed_positions = xnew;
        export_frame(outdir, frame_index, state.deformed_positions, ref_mesh.tris);
    }

    auto sim_end = Clock::now();
    const double total_sim_ms = std::chrono::duration<double, std::milli>(sim_end - sim_start).count();

    std::cout << "\nSimulation finished.\n";
    std::cout << "Total simulation time: " << std::fixed << std::setprecision(3) << total_sim_ms << " ms\n";
    std::cout << "Total solver time:     " << total_solver_ms << " ms\n";
    std::cout << "Average solver time:   " << (total_solver_ms / num_frames) << " ms/frame\n";
    std::cout << "Frames written to:     " << outdir << "\n";

    return 0;
}